### ISSUE TITLE
Nodes with interface set to '*' report invalid IP address, fails assert

### ISSUE THREAD

**Issue by jossgray** [zeromq/zyre#249]
If a zyre node connects to another node,  where the interface has been set to `*`,

```
zyre_t* self = zyre_new("test_node");
zyre_set_interface(self, "*")
```

zyre events report an IP address of 0.0.0.0 and the following assertion fails.

```
Assertion failed: Can't assign requested address (..\..\..\..\src\tcp_connecter.
cpp:316)
```

**Comment by twhittock** [comment]
This appears to be a bug in zbeacon - it returns 0.0.0.0 as the hostname when interface = "*". This then gets transmitted out to zyre_node_start and we bind self->inbox to tcp://0.0.0.0:* - it should probably be *:* instead, and I guess ZMQ will handle the bind correctly then. Will submit a patch...

**Comment by twhittock** [comment]
I've patched zbeacon locally to return a hostname of \* which fixes the initial issue, but then the endpoint sent to other machines in the zre_msg consists of tcp://*:<ephemeral port> which is useless.

ZeroMQ doesn't seem to have a way to determine what address a message was received from. I think this is not solvable using ZMQ.

The GET_FD stuff in libzmq is available, but I don't think that would work with router socket types very well... Any other suggestions would be appreciated.

**Comment by twhittock** [comment]
Uh, I'll just use the hostname for the public endpoint, just like the gossip code does, just below... Pull request incoming.
