### ISSUE TITLE
Problem: No adapter found, ZSYS_INTERFACE= isn't helping

### ISSUE THREAD

**Issue by jemc** [zeromq/zyre#290]
We keep seeing the following error in the self tests in the travis build:
```
Running zyre selftests...
 * zyre: OK
 * zyre_event: E: 14-11-13 23:00:48 No adapter found, ZSYS_INTERFACE= isn't helping
```

I've also seen it occasionally on my own local builds.

I'm not sure if this is actually a problem with zyre or a problem with czmq upstream, but I'm opening the issue here so we can track it.

**Comment by hintjens** [comment]
@jemc can I close this issue?
