### ISSUE TITLE
Network slowdown when zyre starts...

### ISSUE THREAD

**Issue by sanandak** [zeromq/zyre#301]
When I run the chat example the network slows down significantly.  Ping to google.com changes from 10s of ms to many seconds.  This is on a mac os x as well as on a virtual box vm running linux.

I started running chat at seq=17 and stopped it at 23
64 bytes from 173.194.121.46: icmp_seq=16 ttl=52 time=32.547 ms
64 bytes from 173.194.121.46: icmp_seq=17 ttl=52 time=23.332 ms
Request timeout for icmp_seq 18
Request timeout for icmp_seq 19
Request timeout for icmp_seq 20
64 bytes from 173.194.121.46: icmp_seq=18 ttl=52 time=3613.918 ms
64 bytes from 173.194.121.46: icmp_seq=19 ttl=52 time=2618.666 ms
64 bytes from 173.194.121.46: icmp_seq=23 ttl=52 time=452.503 ms
64 bytes from 173.194.121.46: icmp_seq=24 ttl=52 time=369.549 ms
64 bytes from 173.194.121.46: icmp_seq=25 ttl=52 time=286.821 ms

I tried the new zyre api thinking that would help but it doesn't:
The file below uses the new zyre API (zyre_event_new()) and that is where the slowdown occurs. Here I have the same result - a slowdown of the network.  Anybody else experienced this?

https://gist.github.com/ca279f02fe410bb9b14f.git
zyre: 1 1 0
czmq: 3 0 1
I: 15-01-24 12:43:17 (685021) JOIN group=GLOBAL

Thanks,
Sridhar

**Comment by hintjens** [comment]
I can't read that gist, the page is empty for some reason.

This is not normal behaviour, it sounds like something is hammering the
network with traffic, either Zyre or something else. Normally the chat
example does barely anything. You could try running Zyre with verbose
tracing enabled to see if it's looping in some way.

**Comment by jemc** [comment]
I've been seeing this too while working on edgenet/hydra.

Running under wireshark, I see that as soon as I start `hydrad` I get a flood of UDP packets on port 5670 (shown in wireshark as `zre-disc`).  I gets roughly 3300 datagrams per second from my machine (192.168.0.5) to the broadcast address (192.168.0.255).

**Comment by hintjens** [comment]
OK, reproduced it. There's a bug in zbeacon, I think. Chasing this down...

**Comment by hintjens** [comment]
Fixed by https://github.com/zeromq/czmq/pull/902

**Comment by sanandak** [comment]
Thanks.
Sridhar

PS, zmq is the greatest thing since sliced bread.  My students and I have
built a set of instruments in which I had thought to use zmq to connect
between the nodes and the base station. But in the end I used ZMQ in the
data acquisition code itself - it simplified the architecture enormously -
all the data are passed around as ZMQ messages.  So much easier than pipes
or traditional sockets or shared memory...  And if you want to add another
processing step, just subscribe to the right endpoint and bob's your
uncle.  The only part that was problematic was how to discover each other -
and zyre looks like it will solve that...

Thanks!

**Comment by hintjens** [comment]
:-) it's nice to hear such stories. If you ever write up your experiences
as an article online, let me know so I can tell other people about it.
