### ISSUE TITLE
catching interrupt in spawned thread 

### ISSUE THREAD

**Issue by phil0stine** [zeromq/zyre#318]
Since `zyre_recv` uses `zactor_t` to process messages, I expected that a call to `zyre_event_new`, regardless whether from a main or spawned thread, would catch an interrupt signal. 

However, the following example hangs. Is there something obvious missing?
```c++
#include <iostream>
#include <czmq.h>
#include <zyre.h>
#include <thread>
#include <atomic>

class InterruptWait
{
public:
  InterruptWait()
  {
    interrupted_=false;
    node_ = zyre_new("test");
  }
  void wait()
  {
    while (true)
    {
      interrupted_=zsys_interrupted;
      std::cout<<"interrupted? "<<zsys_interrupted<<std::endl;
      zyre_event_new(node_); // Doesnt catch signal 
      if (zsys_interrupted) break;
      zclock_sleep (1000);
    }
  }

  void async_spin()
  {
    event_thread_ = new std::thread(std::mem_fn(&InterruptWait::wait), this);
  }

  zyre_t* node_;
  std::thread* event_thread_;
  std::atomic_bool interrupted_;
};


int main (int argc, char *argv [])
{
  InterruptWait w;
  w.async_spin();
  while (!w.interrupted_.load()) {
    std::cout<<"main"<<std::endl;
    zclock_sleep (1000);
  }
  zclock_log("zsys_interrupted=%d", zsys_interrupted);
  return 0;
}

```

**Comment by sappo** [comment]
`zyre_event_new ()` and `zyre_recv` will return `NULL` if they were interrupted. They won't modify the `zsys_interrupted` variable though if that's what you're expecting.

**Comment by phil0stine** [comment]
Ok. I expected that an interrupt would automatically cause `zyre_event_new` to return `NULL`, without any explicit code on my end having to catch the signal. 

If `zyre_event_new` is called from the main thread, this is the case. However, as in the above case, if called in a separate thread, the call does not return on interrupt.

**Comment by hintjens** [comment]
I suspect zyre_event_new () needs fixing to work in this case.

**Comment by hintjens** [comment]
Just checked and it all looks fine.

**Comment by phil0stine** [comment]
Ok it might be an issue with the above example then, perhaps not a typical use case or wrong pattern. For a workaround, I can explicitly check for `zsys_interrupted` in the main loop to bring down the spawned thread.

**Comment by phil0stine** [comment]
Not sure if this belongs in czmq at this point, but I made an even more min MWE. The interrupt loop is copied from the [zsys_test](http://czmq.zeromq.org/manual:zsys) for a pipe, with the only difference being that this example does not send any string before it calls `str_recv`, to ensure that `str_recv` is indeed being interrupted as I would expect. 

Switching the `spawn_thread` variable will demonstrate the different behaviors.

Not sure if this is an edge case or an incorrect understanding of `recv`, but Id like to learn which it is.
```c++
void interrupt_loop()
{
  zsock_t* pipe_back;
  zsock_t* pipe_front = zsys_create_pipe(&pipe_back);
  while (true)
  {
    std::cout<<"msg test interrupted? "<<zsys_interrupted<<std::endl;
    if (zsys_interrupted) break;
    char *test_string = zstr_recv (pipe_back);
    if (test_string == NULL) std::cout<<" recv returned NULL "<<std::endl;
    else std::cout<<"recv returned "<<test_string<<std::endl;
    free(test_string);
    zclock_sleep (1000);
  }
}

int main (int argc, char *argv [])
{
  bool spawn_thread=false;
  if (spawn_thread)
  {
    std::thread event_thread(interrupt_loop);
    event_thread.join();
  }
  else interrupt_loop();
  zclock_log("zsys_interrupted=%d", zsys_interrupted);
  return 0;
}

```

**Comment by twhittock** [comment]
if the interrupt is delivered to the main thread, czmq isn't going to know about it. signals and threads don't really mix well. what happens if you use zctx_new on the main thread if spawn_thread is true? how about using pthread_sigmask to disable signals on the main thread?

**Comment by phil0stine** [comment]
In the top example I call `zyre_new` in the main thread, I also tried calling in the spawned thread with the same result. I dont want to disable signals in the main thread, I think the fundamental problem is that I thought a signal, once caught in the main thread, would be propagated to the other threads. Apparently not (Im not sure how thatd be implemented). Thanks for the help

**Comment by twhittock** [comment]
So this is resolved for you?

**Comment by phil0stine** [comment]
If I could get some verification as to whether what I expected is even possible, it would be appreciated. Either way Ill mark as closed.
