### ISSUE TITLE
Zyre assertion timeout caused by Leap Second Update

### ISSUE THREAD

**Issue by DaiyuHurst** [zeromq/zyre#322]
Hi Folks, just passing this along, and as I am inclined to believe the emulator developers have not updated to the latest version of Zyre, this problem may have already been fixed.

The system was idling, when suddenly:

dps8: /home/cac/Projects/Multics/dps8m-zmq/zyre-master-9d7e62d2c9/src/zyre_node.c:847: zyre_node_actor: Assertion `timeout <= 1000' failed.

The system was just idling; but interestingly, the system log shows:

[787333.363594] Clock: inserting leap second 23:59:60 UTC

The last modification date on the emulator log file:

-rw-rw-r-- 1 cac cac       5261 Jun 30 16:59 start_sve.log

The zyre code:
Hide message history
```c
    //  Loop until the agent is terminated one way or another
    int64_t reap_at = zclock_time () + REAP_INTERVAL;
    while (!self->terminated) {
        int timeout = (int) (reap_at - zclock_time ());
        assert (timeout <= REAP_INTERVAL);
        if (timeout < 0)
            timeout = 0;

        zsock_t *which = (zsock_t *) zpoller_wait (self->poller, timeout);
```

It sure looks like the leap second messed up the timeout calculation.

**Comment by jemc** [comment]
It sounds like this usage of `zclock_time` will have to be replaced with `zclock_mono` (a monotonically-increasing clock).

**Comment by Asmod4n** [comment]
```zclock_time``` is used quite often, is it save to just replace all of it with ```zclock_mono``` ?

**Comment by hintjens** [comment]
Yes, this is the correct fix. I think we should deprecate zclock_time in
fact. It has no other use afaik.
