### ISSUE TITLE
Feature: Set port for gossip protocol

### ISSUE THREAD

**Issue by aletheia7** [zeromq/zyre#323]
I would like the ability to set the port for the gossip protocol. I use a firewall on all of my machines. The default ephemeral port means I have to create a new firewall rule, and potentially remove an old firewall rule, to allow the new port every time I start the application. In addition, creating a firewall rule means I have to have escalated root/admin privileges. This is something I would like to avoid if possible.

Thank you for creating the Zyre protocol.

**Comment by sappo** [comment]
Hi @aletheia7,
the Readme.md is a bit out of date but take a look at the zyre.h https://github.com/zeromq/zyre/blob/master/include/zyre.h. There are two methods to bind and connect the gossip protocol which allows you to choose the protocol e.g. inproc or tcp and allows you to specify a tcp port of your choosing.

**Comment by aletheia7** [comment]
Using the bind and connect methods in the gossip protocol will disable the beacon feature  zyre.

Thank you for your assistance.

**Comment by hintjens** [comment]
@aletheia7 there is no way to use both beaconing and gossip, since that would mean nodes are on different networks, and cannot speak to each other. Zyre uses either one, or the other. If you don't configure the gossip endpoints, it uses beaconing. If you do configure them, it uses gossip. 

I'm closing this issue then.

**Comment by aletheia7** [comment]
I do not think I understand your comment. Beacon and gossip are always on the the same network. Otherwise the hosts would not be able to talk to each other. Why would specifying a port for the router socket of the node, as opposed to using an ephemeral port, suddenly prevent gossip nodes from communicating via dealer -> router?

Beacon can listen on port 5760. Gossip can listen on say, 9999. How is this different from Beacon listening on port 5760 and Gossip listening on a random port?

**Comment by Asmod4n** [comment]
@hintjens i guess whats missing: manually setting a port for the beacon socket which gets advertised, just like you can do with the gossip stuff.

@aletheia7 different networks means they aren't on the same subnet, the UDP "broadcasts" from the beacon protocol don't leave their subnet. With the gossip protocol routing into different networks is possible.

**Comment by aletheia7** [comment]
You can set the port for the Beacon. You cannot set the port for the Gossip.

**Comment by Asmod4n** [comment]
https://github.com/zeromq/zyre/blob/master/include/zyre.h#L90

**Comment by aletheia7** [comment]
Yes, you can set the port for Gossip, but then you lose Beacon. I do not want to loose Beacon.

**Comment by Asmod4n** [comment]
I am at a loss at to what you wanna do, gossip and beaconing at the same time? Thats not possible with one zyre actor. You can start two zyre actors, one with UDP beaconing and the other with the gossip protocol and forward the events between them.

**Comment by aletheia7** [comment]
Correct me if I'm wrong, but every node runs the same stack; i.e. beacon and gossip with the default zyre. I just want to choose the port for the router in gossip and leave beacon on 5760.

**Comment by sappo** [comment]
@aletheia7 to wrap this up: What you like to have is, beacon discovery on the local subnet and on beacon discovery add the discovered zyre node to the gossip network?!?

**Comment by aletheia7** [comment]
That's the way zyre already works.

**Comment by sappo** [comment]
No ... okay let's take this from another angle. Could you please describe the problem you would like to solve, because I'm confused and don't understand the issue you are having.

**Comment by aletheia7** [comment]
I am using the go version of zyre (gyre) located here: https://godoc.org/github.com/zeromq/gyre

The interaction of beacon and gossip is described here: http://hintjens.com/blog:32

Example:
server_a starts a beacon and publishes a udp destination port 5760 packet with a uuid and random port of a router socket. server_b beacon listens on udp port 5760, gets the packet and connects with a dealer socket to the random port from server_a. Problem: server_b dealer cannot talk to server_a router endpoint when server_a blocks the random IANA port with a firewall. Therefore, this request is to add a feature to stipulate a specific port instead of using a random port.

The Gyre object combines the Beacon and Gossip functionality described in blog:32.

**Comment by Asmod4n** [comment]
gyre also either uses beaconing or gossip, not both. like zyre.

**Comment by aletheia7** [comment]
linux "netstat -tulpon" shows Gyre listening on udp:5760 and an ephemeral router port. I want to set the port. Have you read blog:32? Both technologies are being used in Gyre at the same time. One instance of Gyre does both.

**Comment by Asmod4n** [comment]
here is the part which decides if beacon or gossip starts: https://github.com/zeromq/zyre/blob/master/src/zyre_node.c#L159

what you want to change is most likely https://github.com/zeromq/zyre/blob/master/src/zyre_node.c#L178

**Comment by Asmod4n** [comment]
gyre also disables beacon when gossip is enabled: https://github.com/zeromq/gyre/blob/master/node.go#L118

**Comment by aletheia7** [comment]
How do I use beacon and set the router port broadcasted through the beacon?

**Comment by Asmod4n** [comment]
Thats currently not implemented as it seams, you could create a patch for it.

**Comment by sappo** [comment]
@aletheia7 I guess what you're looking for is https://github.com/zeromq/zyre/blob/master/include/zyre.h#L77

**Comment by aletheia7** [comment]
How does anyone use zyre/gyre behind a firewall?

**Comment by aletheia7** [comment]
Beacon is nice, but fails with the ephemeral port. Beacon already agrees to use 5760. Just set another port for the router and then setup the firewall to allow both ports. Then beacon can be useful. Otherwise, you have to either disable the firewall or dynamically modify the firewall with a non-root process.

**Comment by sappo** [comment]
Feel free to implement the changes that solve your problem for zyre/gyre and send in a pull request which we're happy to merge.

**Comment by stephan57160** [comment]
Any news, on this topic, since then ?

**Comment by sappo** [comment]
You can bind the gossip server with any supported zeromq protocol. E.g.
inproc or tcp. And for tcp you are free to choose your own port.

Stephan <notifications@github.com> schrieb am Di., 31. Juli 2018, 11:52:

**Comment by stephan57160** [comment]
OK ok ok ok.
Actually, I have the same trouble than aletheia7.
The firewall is embedded on my Linux box. As the ephemeral port is ... kind of random ...
I have some problems to fix the firewall rules.

What about a patch, to force TCP port, when we want to use BEACON and not GOSSIP ?
Or maybe, you prefer a PULL REQUEST ?

**Comment by stephan57160** [comment]
Read somewhere in zyre.h:

```
    //  By default, Zyre binds to an ephemeral TCP port and broadcasts the local 
    //  host name using UDP beaconing. 
```
As far as I understood, there are 2 ports involved, not only one, when BEACON is used:
- UDP port, with default 5670, used in multicast for the discovery,
- TCP port (ephemeral)

zyre_set_port() will set the UDP port, but there is no way to fix the TCP one.

The problem with the ephemeral port is that it's choosen by the kernel, via:
```
    self->port = zsock_bind(self->inbox, "tcp://%s:*", hostname);
```
There, we have no constant, nothing "frozen" to setup in firewall rules.

**Comment by aletheia7** [comment]
The go smudge project provides similar gossip protocol (SWIM) functionality: https://github.com/clockworksoul/smudge

**Comment by yvs2014** [comment]
> Read somewhere in zyre.h:
> ```
>     //  By default, Zyre binds to an ephemeral TCP port and broadcasts the local 
>     //  host name using UDP beaconing. 
> ```
> As far as I understood, there are 2 ports involved, not only one, when BEACON is used:
> * UDP port, with default 5670, used in multicast for the discovery,
> * TCP port (ephemeral)

   Sorry for intervening in this old discussion topic, I'd like to clarify one point: multicast or broadcast?
   If it's about multicast discovery, how can one set up a multicast address for discovery?

**Comment by sphaero** [comment]
I'm not sure multicast is even supported. It is supported in theory. I have experimented with it once. However I don't think it is exposed. So only broadcast is available. It's quite easy to support it though but it would require a PR. 

And since libzmq supports UDP zbeacon should be adapted to use it. Would make it more portable.

**Comment by yvs2014** [comment]
Thanks for answer.
So, with zbeacon, it should've, but still has not.  What about gossip discovery with bind/connect("(e)pgm://multicast-address") instead of zbeacon? Will it work?

**Comment by sphaero** [comment]
As I said. I'm not sure. But if you read the code you'll find answers. It seems it does have some stuff for multicast: https://github.com/zeromq/czmq/blob/d4b1a1d884532e43e82b9055ceb0b84d1db5915c/src/zbeacon.c#L312

**Comment by yvs2014** [comment]
> As I said. I'm not sure. But if you read the code you'll find answers. It seems it does have some stuff for multicast: https://github.com/zeromq/czmq/blob/d4b1a1d884532e43e82b9055ceb0b84d1db5915c/src/zbeacon.c#L312

Okay, I see, thanks for dispatching

**Comment by yvs2014** [comment]
Upd: with a small patch it works

**Comment by sphaero** [comment]
:+1:  We'd appreciate a PR if it is useful to others!

**Comment by yvs2014** [comment]
done
https://github.com/zeromq/czmq/pull/2177
