### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by blakemcbride** [zeromq/zyre#326]
Cool if you guys could add a BUILD.txt file.

**Comment by blakemcbride** [comment]
autoconf gives:

configure.ac:19: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:33: error: possibly undefined macro: AC_SUBST
configure.ac:52: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:53: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:54: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:60: error: possibly undefined macro: AC_ARG_WITH
configure.ac:60: error: possibly undefined macro: AS_HELP_STRING
configure.ac:79: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:116: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:264: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:279: error: possibly undefined macro: AM_COND_IF
configure.ac:279: error: possibly undefined macro: AC_MSG_NOTICE


I am 64 bit LinuxMint.  Autoconf 2.69

**Comment by blakemcbride** [comment]
./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force -I config
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --include=config --force
configure.ac:33: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:53: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:54: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:60: error: possibly undefined macro: AC_ARG_WITH
configure.ac:60: error: possibly undefined macro: AS_HELP_STRING
configure.ac:79: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:116: error: possibly undefined macro: AC_CHECK_LIB
autoreconf: /usr/bin/autoconf failed with exit status: 1
autogen.sh: error: autoreconf exited with status 1

**Comment by hintjens** [comment]
Sounds like you have a problem with autoconf. Old version?

Does CZMQ build?

**Comment by blakemcbride** [comment]
I have version 2.69 - what comes with my Linux distro.  Is that the problem?

Also, I've been trying all sorts of things.  If I knew the official procedure I could cut my problem in half.  Could you please provide me with the exact specific step to build?

Thanks!

**Comment by sappo** [comment]
As always
```sh
./autoconf.sh
./configure.sh
make && make check
make install
```

**Comment by blakemcbride** [comment]
Thanks!  Should 2.69 be okay?

**Comment by sappo** [comment]
Yes, works for me.
Am 30.08.2015 00:20 schrieb "Blake McBride" <notifications@github.com>:

**Comment by blakemcbride** [comment]
blake@blake-sony ~/Backup/zyre $ git pull
Already up-to-date.
blake@blake-sony ~/Backup/zyre $ rm -rf *
blake@blake-sony ~/Backup/zyre $ ls -al
total 20
drwxr-xr-x 3 blake blake 4096 Aug 29 17:25 .
drwxr-xr-x 5 blake blake 4096 Aug 29 13:53 ..
drwxr-xr-x 8 blake blake 4096 Aug 29 17:25 .git
-rw-r--r-- 1 blake blake  873 Aug 28 16:20 .gitignore
-rw-r--r-- 1 blake blake  213 Aug 28 16:20 .travis.yml
blake@blake-sony ~/Backup/zyre $ git checkout --force
Your branch is up-to-date with 'origin/master'.
blake@blake-sony ~/Backup/zyre $ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
blake@blake-sony ~/Backup/zyre $ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force -I config
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --include=config --force
configure.ac:33: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:53: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:54: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:60: error: possibly undefined macro: AC_ARG_WITH
configure.ac:60: error: possibly undefined macro: AS_HELP_STRING
configure.ac:79: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:116: error: possibly undefined macro: AC_CHECK_LIB
autoreconf: /usr/bin/autoconf failed with exit status: 1
autogen.sh: error: autoreconf exited with status 1
blake@blake-sony ~/Backup/zyre $ sudo apt-get install libtool
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtool is already the newest version.
blake@blake-sony ~/Backup/zyre $ sudo apt-get install gettext
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gettext is already the newest version.
blake@blake-sony ~/Backup/zyre $ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
blake@blake-sony ~/Backup/zyre $


Do you have any suggestions?

My opinion is that your environment, as well as others who are using your package, are currently assuming something not being checked.  You just have it right through historical reasons.

**Comment by twhittock** [comment]
Have you tried

apt-get install pkg-config

**Comment by blakemcbride** [comment]
$ sudo apt-get install pkg-config
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version.
$ pkg-config --version
0.26

**Comment by Asmod4n** [comment]
Try ```apt-get install build-essential```, do you have autoreconf installed?

**Comment by blakemcbride** [comment]
blake@blake-sony ~ $ sudo apt-get install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
blake@blake-sony ~ $ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
blake@blake-sony ~ $ 


Thanks for the help!

**Comment by Asmod4n** [comment]
Hm, i believe someone has packaged zmq, czmq and zyre for debian, it should be in unstable or testing.

**Comment by mgruendler** [comment]
Installing the pkgconfig module works also fine on MacOS and resolves the issue:

`sudo port install pkgconfig`

**Comment by bluca** [comment]
In the past year and a half there have been a ton of changes to the build system via zproject, and we test it extensively on all main distributions, so it should be fine now. Please reopen if this is still an issue.

**Comment by darmie** [comment]
@mgruendler that didn't fix it for me :(
