### ISSUE TITLE
ztester_gossip

### ISSUE THREAD

**Issue by anrl** [zeromq/zyre#345]
I ran the ztester_gossip example that is included with zyre. 
I got the following error.

Assertion failed: !more (src/fq.cpp:117)

It is related to multi-part message reception from what I can tell.
I am running this on OS X 10.11.

I have compiled and installed the latest versions of zmq, czmq, and zyre from the github repositories.

**Comment by hintjens** [comment]
Can you try increasing the number of file handles per process:

http://zeromq.org/docs:tuning-zeromq#toc1

**Comment by anrl** [comment]
I have increased it to 50000.

sysctl -a | grep maxfiles
kern.maxfiles: 300000
kern.maxfilesperproc: 50000

Still.. it is not working.

**Comment by hintjens** [comment]
OK, I get the same crash on Linux; it's not an OS/X issue. Thanks for
reporting it.

**Comment by hintjens** [comment]
OK, I'm going to ask the zeromq-dev list, this is old code in libzmq. I'm
curious why it's breaking now.

**Comment by anrl** [comment]
Thanks a lot for checking it out.

**Comment by bluca** [comment]
Closing as this problem was fixed in libzmq by https://github.com/zeromq/libzmq/pull/1645
