### ISSUE TITLE
Problem: zyre-jni can't create a shared library for Android

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/zyre#347]

**Comment by jemc** [comment]
You might find the [`qt-android`](https://github.com/zeromq/zyre/tree/master/builds/qt-android) build system in this repository to be of help - I've been using it to create shared libraries for android for a while now.  I happen to use them with Qt, but there is nothing Qt-specific about the process, so they should work in your context as well, perhaps with a bit of tweaking.

**Comment by trevorbernard** [comment]
@jemc, that's what I have been looking at. I'm just trying to understand how it works ATM

**Comment by jemc** [comment]
Basically, all it does is build the library and all dependencies using the specified android cross compiler toolchain, then uses `readelf` to check for some common problems that can prevent loading from `dlopen` in subtle ways if the libraries were not built correctly.

**Comment by hintjens** [comment]
This is now solved.
