### ISSUE TITLE
zyre jni binding test is failing

### ISSUE THREAD

**Issue by awynne** [zeromq/zyre#356]
./gradlew test produces the failing test report

```
java.lang.UnsatisfiedLinkError: org.zeromq.zyre.ZyreEvent.__test(Z)V
	at org.zeromq.zyre.ZyreEvent.__test(Native Method)
	at org.zeromq.zyre.ZyreEvent.test(ZyreEvent.java:103)
	at org.zeromq.zyre.ZyreEventTest.test(ZyreEventTest.java:16)
```

**Comment by awynne** [comment]
i think this is a remaining issue from the zproject changes @hintjens is working on

**Comment by hintjens** [comment]
Yes, same issue with czmq still.

**Comment by awynne** [comment]
zyre jni build is failing again. PR #361 partially fixes this.  The remaining issues are lingering issues with self pointers:

-> gradle build
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/home/wya1pi/dev/git-repos/awynne/zyre/bindings/jni/src/main/java/org/zeromq/zyre/ZyreEvent.java:29: error: incompatible types: long cannot be converted to Zyre
        self = __new (self.self);
                     ^
/home/wya1pi/dev/git-repos/awynne/zyre/bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java:185: error: self is not public in Zmsg; cannot be accessed from outside package
        return __whisper (self, peer, msgP.self);
                                          ^
/home/wya1pi/dev/git-repos/awynne/zyre/bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java:193: error: self is not public in Zmsg; cannot be accessed from outside package
        return __shout (self, group, msgP.self);
