### ISSUE TITLE
Does not compile with C++ since declaration of zyre_print is missing

### ISSUE THREAD

**Issue by tompe17** [zeromq/zyre#364]
I had to do
```
#include "zyre.h"
extern "C" {
  void zyre_print(zyre_t * self);
}
```
to work around this issue.

**Comment by sappo** [comment]
The problem is that the api for code generation has changed and the
excluded print method needs to be removed from the xml. I can do it later.
Am 07.12.2015 3:51 nachm. schrieb "tompe17" <notifications@github.com>:

**Comment by hintjens** [comment]
I'll fix this, just a second...
