### ISSUE TITLE
problem: in jni binding, call to no-arg constructor fails

### ISSUE THREAD

**Issue by awynne** [zeromq/zyre#366]
The following code causes the error: "java: src/zyre.c:305: zyre_start: Assertion `self' failed."

	public static void main(String[] args) {
		Zyre zyre = new Zyre();
		zyre.start();

calling the Zyre(String) constructor works fine

**Comment by hintjens** [comment]
OK, fixed in zyre master, by removing this constructor. It was there to allow tests to run, and did not work for applications. I've switched to using a static method for Zyre.test () so there's no need for this dummy constructor.

**Comment by awynne** [comment]
OK. Thanks
