### ISSUE TITLE
Problem: in jni-binding, ctrl-c does not exit

### ISSUE THREAD

**Issue by awynne** [zeromq/zyre#367]
This class (https://gist.github.com/awynne/188d60156309b8d922a8) demonstrates that you cannot exit a a running zyre-jni program with ctrl-c.  If you run the program, you can exit normally by calling zyre.close() -- this happens in the program by typing "exit".  However, typing Ctrl-c does not exit the program.  Only kill -9 will stop the program.

This does not appear to be a java problem.  If you add a shutdownhook, it never gets called when ctrl-c is pressed.  Thus is appears that zyre is catching the signal, but not responding to this.  perhaps this has something to do with jni??

**Comment by hintjens** [comment]
OK, I've pushed a fix to Zyre though I'm not sure it's the right thing. What we do now is disable CZMQ's interrupt handling. This means any SIGINT will come through to Java. 

The alternative, which I'll discuss with other binding authors, is to expose the same API we use in C apps, namely an interrupt flag, and NULL on blocking recvs. So, the main loop changes from:

            while (true) {

to

        while (!zsys.interrupted ()) {

assuming we add a zsys package.

**Comment by awynne** [comment]
Thanks for the quick fix.  I also support the alternative option as a long
term solution .
