### ISSUE TITLE
problem in jni binding: version mismatch between zyre and czmq

### ISSUE THREAD

**Issue by awynne** [zeromq/zyre#377]
zyre's build.gradle depends on czmq-jni version 0.1.0, while the latest czmq-jni is at 3.0.3.  I'm not sure which one is correct.

**Comment by hintjens** [comment]
I fixed this problem today, though I'm not sure my solution is the right
one. We don't know the current CZMQ version in Zyre, so it uses the minimum
required version, which defaults to 0.0.0. I just made the pull request.

**Comment by awynne** [comment]
@hintjens, I think the correct way to do this is to use the '+' notation.  I got it working locally with this dependency:

```compile 'org.zeromq:czmq-jni:3.0+'```

I think this only works within the same major version because these versions don't work: "1.0+" and "0.0+"

**Comment by hintjens** [comment]
Hmmm, getting the actual version of dependencies is tricky. I'm going to
have to make some changes to zproject. I've made an issue:
https://github.com/zeromq/zproject/issues/397

**Comment by awynne** [comment]
@hintjens Actually, I just tested some more and the following works!

```compile 'org.zeromq:czmq-jni:+'```

this means 'any version'

**Comment by hintjens** [comment]
OK, that makes things a *lot* simpler... :-)
