### ISSUE TITLE
can not build using vs 2013

### ISSUE THREAD

**Issue by yindongfei** [zeromq/zyre#383]
the sln can not open by vs 2013.
some dependency lost, like czmq, libzmq or something else i do not know.
after I download the dependency, where should i put?
or is there any tutorial to follow?

**Comment by hintjens** [comment]
My fault, I am changing the MSVC builds and I'm working on fixing this, if you can wait a little while. You could also try checking out #b4d941 which is the last commit before I broke the MSVC builds.

**Comment by yindongfei** [comment]
thanks for your reply, I will try it
