### ISSUE TITLE
Android binding build hangs

### ISSUE THREAD

**Issue by vimalanandans** [zeromq/zyre#404]
## running build.sh hangs

../czmq/bindings/jni/android$ ./build.sh 
*******\*  Building CZMQ Android native libraries

**Comment by hintjens** [comment]
Can you run "set -x" to enable script tracing and then see where it hangs?

**Comment by vimal-gsv** [comment]
Still hangs...no clue

I am using ubuntu virtual box. is this problem any means.
---------------------------
vnd2kor@pitt:~/bezirk/git/tmp/czmq/bindings/jni/android$ set -x
vnd2kor@pitt:~/bezirk/git/tmp/czmq/bindings/jni/android$ ./build.sh 
+ ./build.sh
********  Building CZMQ Android native libraries

**Comment by hintjens** [comment]
Sorry, kindly edit build.sh and add 'set -x' into the script e.g. around line 20. This will show its progress.

**Comment by vimal-gsv** [comment]
change set -e to set -x. here is the log

vnd2kor@pitt:~/bezirk/git/tmp/czmq/bindings/jni/android$ ./build.sh
+ export ANDROID_API_LEVEL=android-8
+ ANDROID_API_LEVEL=android-8
+ export ANDROID_SYS_ROOT=/home/vnd2kor/Android/android-ndk-r10e/platforms/android-8/arch-arm
+ ANDROID_SYS_ROOT=/home/vnd2kor/Android/android-ndk-r10e/platforms/android-8/arch-arm
+ '[' '' = -d ']'
+ source ../../../builds/android/android_build_helper.sh
++ '[' -z '' ']'
++++ dirname ../../../builds/android/android_build_helper.sh
+++ cd ../../../builds/android
+++ pwd
++ ANDROID_BUILD_DIR=/home/vnd2kor/bezirk/git/tmp/czmq/builds/android
++ ANDROID_BUILD_FAIL=()
+ android_build_env
+ '[' -z /home/vnd2kor/Android/android-ndk-r10e ']'
+ '[' -z /home/vnd2kor/Android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/ ']'
+ '[' -z arm-linux-androideabi-4.8 ']'
+ '[' -z arm-linux-androideabi ']'
+ '[' -z arm ']'
+ android_build_check_fail
+ '[' '!' 0 -eq 0 ']'
+ '[' '!' -d /home/vnd2kor/Android/android-ndk-r10e ']'
+ '[' '!' -d /home/vnd2kor/Android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/ ']'
+ ANDROID_BUILD_SYSROOT=/home/vnd2kor/Android/android-ndk-r10e/platforms/android-9/arch-arm
+ '[' '!' -d /home/vnd2kor/Android/android-ndk-r10e/platforms/android-9/arch-arm ']'
+ ANDROID_BUILD_PREFIX=/home/vnd2kor/bezirk/git/tmp/czmq/builds/android/prefix/arm-linux-androideabi-4.8
+ mkdir -p /home/vnd2kor/bezirk/git/tmp/czmq/builds/android/prefix/arm-linux-androideabi-4.8
+ android_build_check_fail
+ '[' '!' 0 -eq 0 ']'
+ echo '********  Building CZMQ Android native libraries'
********  Building CZMQ Android native libraries
+ cd ../../../builds/android
+ ./build.sh

**Comment by hintjens** [comment]
Could you add the same line to czmq/builds/android/build.sh? Thanks.

**Comment by vimal-gsv** [comment]
it running in a infinite loop i guess
[Uploading zyre build error.txt…]()

**Comment by vimal-gsv** [comment]
closed accidently

**Comment by hintjens** [comment]
Looking at the log, it seems you've set LIBZMQ_ROOT to the CZMQ directory. As a result the build.sh calls itself over and over, hence loops forever.

My advice is to check out libzmq, czmq, and zyre at the same level, and set only the necessary environment variables for Android building:

     ANDROID_NDK_ROOT=$HOME/android-ndk-r10e
     TOOLCHAIN_NAME=arm-linux-androideabi-4.9
     TOOLCHAIN_VERSION=4.9
     TOOLCHAIN_HOST=arm-linux-androideabi
     TOOLCHAIN_ARCH=arm
     TOOLCHAIN_PATH=$ANDROID_NDK_ROOT/toolchains/$TOOLCHAIN_NAME/prebuilt/linux-x86_64/bin

**Comment by bluca** [comment]
Closing as there was no response in a year and it looked like a local configuration error. Please reopen if you still see this.
