### ISSUE TITLE
Zyre chat example does not compile, misses a zyre.h

### ISSUE THREAD

**Issue by zoobab** [zeromq/zyre#406]
From commit 99ac0e07a43838829b53a55aaf3244ed614e7224, the "make" does not work:

make[4]: Entering directory '/home/zoobab/soft/openwrt4/build_dir/target-mips_34kc_musl-1.1.12/zyre'
Making all in doc
make[5]: Entering directory '/home/zoobab/soft/openwrt4/build_dir/target-mips_34kc_musl-1.1.12/zyre/doc'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/zoobab/soft/openwrt4/build_dir/target-mips_34kc_musl-1.1.12/zyre/doc'
Making all in examples/chat
make[5]: Entering directory '/home/zoobab/soft/openwrt4/build_dir/target-mips_34kc_musl-1.1.12/zyre/examples/chat'
  CC       chat.o
chat.c:27:18: fatal error: zyre.h: No such file or directory
compilation terminated.
Makefile:413: recipe for target 'chat.o' failed
make[5]: **\* [chat.o] Error 1

Have the same problem when not cross-compiling on my laptop:

zoobab@chuchu /home/zoobab/soft/zyre-master [40]$ make
Making all in doc
make[1]: Entering directory '/home/zoobab/soft/zyre-master/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/zoobab/soft/zyre-master/doc'
Making all in examples/chat
make[1]: Entering directory '/home/zoobab/soft/zyre-master/examples/chat'
make[1]: **\* No rule to make target '../../src/libzyre.la', needed by 'chat'.  Stop.
make[1]: Leaving directory '/home/zoobab/soft/zyre-master/examples/chat'
Makefile:1229: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

**Comment by zoobab** [comment]
Well it seems that now running "generate.sh" is a required step in order to build zyre, which was not the case previously. I can now build if I first run "generate.sh".

**Comment by jemc** [comment]
@zoobab - it should not be necessary to run `generate.sh` - all files generated by `generate.sh` should be checked into version control.

You can file a PR with the diff from running `generate.sh` to fix the build.

**Comment by jemc** [comment]
Actually, you should be sure you have the latest version of zproject before doing that.
