### ISSUE TITLE
Segmentation fault in nodejs binding

### ISSUE THREAD

**Issue by Dev1an** [zeromq/zyre#432]
When I call the `msg()` method of a `ZyreEvent`. The nodejs app crashes and logs:
`Segmentation fault: 11`

**Comment by hintjens** [comment]
Can you provide a minimal test case for this? Thanks.

**Comment by Dev1an** [comment]
Never mind 1166350ac6f2068647b781b82d80d9ced0e3f13d solved the issue for me.
