### ISSUE TITLE
Problem: Outdated Python binding file

### ISSUE THREAD

**Issue by papr** [zeromq/zyre#468]
https://github.com/zeromq/zyre/blob/master/bindings/python/zyre.py (mostly) duplicates https://github.com/zeromq/zyre/tree/master/bindings/python/zyre and is probably a relic from an old auto-generation.

Solution: Delete https://github.com/zeromq/zyre/blob/master/bindings/python/zyre.py

**Comment by sphaero** [comment]
Seems legit: https://github.com/zeromq/zproject/commit/39b13a6167cf3e2b374769dc9b58129ee7c6334e

Please send a pull request
