### ISSUE TITLE
Can't get get zyre to work over gossip properly

### ISSUE THREAD

**Issue by mschuckmann** [zeromq/zyre#481]
I just started experimenting using the gossip protocol with zyre and I'm having some problems getting it to work properly. I've attempted to use both ipc and tcp gossip transports and both are behaving the same. 

The 2 main problems I'm seeing are: 
1. Only 2 nodes will connect, nothing beyond that. 
2. When one node disconnects the other node doesn't not see the disconnect, eventually the connection will timeout but only after the evasive timeout occurs. Additionally the disconnected node can not reconnect. 

All of the examples I've seen for Zyre and gossip use the inproc transport so I don't know if the ipc and tcp transports have been verified. Can anyone confirm if they should be working?

**Comment by wesyoung** [comment]
i've gotten it to work with the python bindings over tcp. if you're doing this on a VM with many different adapters, you have to make sure both gossip and the main comms channel are configured properly (this involves making sure set_endpoint and bind_gossip are correct). i had to write some python code using netifaces to make it easier, but after that i was able to spin up 3 vbox nodes using vagrant and get them to talk back and forth...

hth

**Comment by mschuckmann** [comment]
Thanks for the response I'm not trying to do it over a VM, right now I really just need ipc  to work and in the future I'll need tcp to work. I've been able to get a bit further with this. I modified the chat example to use ipc and it does work so there must be something wrong with my original implementation that I will have to work out. 

I still can't get the gossip tcp transport to work (I get zyre_peer_connect Assertions and or the connections immediately die).  When you say that set_endpoint and bind_gossip need to be correct can you give an example? 

I've attached my modified chat.c program. 

[chat.c.zip](https://github.com/zeromq/zyre/files/495859/chat.c.zip)

Thanks,
Matt S.

**Comment by wesyoung** [comment]
is "zyre_set_endpoint(node, "tcp://eth0:%s", "*");" supposed to work? (ie: specifying the adapter instead of the tcp address?)

i don't think i've ever seen that. i mean, i had to write some code on the python side to resolve eth0 properly to do what you're trying to do, but did you try binding to tcp://0.0.0.0 ?

**Comment by mschuckmann** [comment]
I don't know if it is supposed to work there is very little documentation on the inputs to zyre_set_endpoint() and zyre_gossip_bind().  I found an example for [zmq_bind()](http://api.zeromq.org/2-1:zmq-bind) that made me think it would work. I will try your suggestion.

**Comment by hintjens** [comment]
Have a look at the zyre.c selftest method.

**Comment by wesyoung** [comment]
you're right. i had forgotten about that... i'll have to go back and re-look at the code. iirc; set_endpoint advertises to the other nodes "this is how to connect to me", so "eth0" wouldn't make sense. bind_gossip may [and i'd have to check] be doing the correct thing though.. 

i was having similar issues where bind_gossip would bind to the correct interface, but then advertise a private address on 'eth0' (where i had 3-4 adapters and was binding to the address on eth1).

re: doc, yupper. right now outside of teh API there's a lot of room for PR's. i'm cleaning up a python bindings example and will try to post that soon(ish) along with the Vagrantfile i'm using to demo multiple TCP sockets over 3+ vms. 

had to do a LOT of .c and .inc reading within zyre and czmq [in addition to the guides] to fully wrap my head around it too. lots of opportunity...

**Comment by wesyoung** [comment]
also; "i had to write some code on the python side to resolve eth0 properly to do what you're trying to do" meaning, to provide gossip with the correct address to advertise given only "an adapter"... if that makes sense (ie: if you tell gossip to bind to eth0, needed some code to resolve what ipv4/v6 address was bound to eth0 and routable via the routing tables, then advertise that address to the gossip mesh...).

**Comment by mschuckmann** [comment]
@hintjens The zyre.c self test uses inproc transport for gossip so it doesn't help me understand how to properly specify tcp or ipc transports.

**Comment by mschuckmann** [comment]
@wesyoung Yes it makes sense that you'd need to figure out the IP for an adaptor, but I found for the UDP beacon mode I could specify an adaptor by name, i.e. zyre_set_interface("eth0") and specifying it by address didn't work so I thought hey maybe it works for zyre_gossip_*() too. 

Your comment "set_endpoint advertises to the other nodes "this is how to connect to me", so "eth0"" was a good one and is helping me get it. I'm getting there slowly.

**Comment by hintjens** [comment]
Ah. Sorry, can't help ATM then.

**Comment by wesyoung** [comment]
see this [very crude] example, it's very czmq non-pythonic atm, but it seems to work across 3+ nodes... it also re-uses some pyzmq logic which makes the example itself harder to read [working on that], but you should get the idea...

https://gist.github.com/wesyoung/0c9176aef9266163d2dfffc8560e36fc

and the vagrant file that helps to bootstrap a test env:

https://gist.github.com/wesyoung/9b9f1aa731b7a29dbb4296625b001b73

where you see: 'node1.vm.box = "zyre"' i had created a box locally from:

https://github.com/zeromq/zyre/blob/master/Vagrantfile

to avoid having to re-compile the box when spinning the nodes up and down.

fwiw.

**Comment by wesyoung** [comment]
@bluca i think this can be closed.

**Comment by sphaero** [comment]
For what it's worth I was working on an example chat client using gossip at the FOSDEM hackathon while being stuck in the train:

https://gist.github.com/sphaero/bea0298d86972b76e7e9d813ed01d197

It works but it could be a cleaner example :)
