### ISSUE TITLE
Free Pascal binding

### ISSUE THREAD

**Issue by cpicanco** [zeromq/zyre#482]
I have written a Free Pascal binding to zyre. However,  I did not test it yet. It has been difficult for me to build Zyre in Debian 8.

I noticed that there is a package, but discussions said it is in a unstable/testing state.

Any help to build the library will be appreciated.
Best,
Rafael

**Comment by bluca** [comment]
You can find Debian 8 built packages on OBS:

https://build.opensuse.org/package/show/home:zeromq:git-stable/zyre
http://download.opensuse.org/repositories/home:/zeromq:/git-stable/Debian_8.0/

For the bindings, Zyre is a zproject project, so all bindings are autogenerated from the zproject's templates. There is no template for Pascal, so I highly encourage to contribute it to zproject's so that it can benefit not only Zyre but any zproject generated library: https://github.com/zeromq/zproject

**Comment by sappo** [comment]
Hi Rafael,
how did you try to build zyre and what probems did you encounter?

//Kevin

Am 03.10.2016 16:23 schrieb "Rafael Picanço" <notifications@github.com>:

**Comment by cpicanco** [comment]
Thank you @bluca. GSL is an interesting approach for professional programmers. However, I am actually a behavioral scientist. I spent 4h to 6h (one day) writing the binding, manually. How much time do you except a non professional like me will take to use GSL?

**Comment by bluca** [comment]
GSL is surprisingly easy to use :-) This is the whole of the Ruby bindings template, about 600 lines: https://github.com/zeromq/zproject/blob/master/zproject_ruby.gsl Similarly for other languages.
Consider this: having your binding as a template, means it's written once and fixed forever. If Zyre or any other library changes, it will be automatically regenerated. Writing it manually means having to manually keep it up to date with the library, every time the APIs change. IMHO it is a worthwhile investment :-)

But of course it's up to you! Let us know what the problems building manually are and we'll try to help.

**Comment by cpicanco** [comment]
I will give GSL a trial. Will be reporting the building errors by night. Thank you for your support.

**Comment by cpicanco** [comment]
Successfully built following the install instruction in the README [76740265ee928dd5b28fc46e921849035ac46ec2]. I guess I had a bad libzmq installation (v3.2.5).

**Comment by cpicanco** [comment]
Work in progress for the binding here: https://github.com/cpicanco/fpc_zyre
