### ISSUE TITLE
Error relocating build/Release/zyre.node: symbol not found

### ISSUE THREAD

**Issue by mrusme** [zeromq/zyre#487]
While building the zyre node binding on my local machine (Mac) works, I tried to do the same inside a Docker container, what unfortunately does not succeed. Building itself runs through, but `ldd` reports missing symbols:

``` bash
/build/zyre/bindings/nodejs # ldd build/Release/zyre.node 
    ldd (0x55a4845c6000)
    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f1f09442000)
    libc.musl-x86_64.so.1 => ldd (0x55a4845c6000)
    libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f1f0922f000)
Error relocating build/Release/zyre.node: _ZN2v814ObjectTemplate21SetInternalFieldCountEi: symbol not found
Error relocating build/Release/zyre.node: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v85Value8ToStringENS_5LocalINS_7ContextEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v88External3NewEPNS_7IsolateEPv: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v85Value9IsBooleanEv: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v88External5ValueEv: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v86String6LengthEv: symbol not found
Error relocating build/Release/zyre.node: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPPNS1_6ObjectE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v811HandleScopeC1EPNS_7IsolateE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v89Exception9TypeErrorENS_5LocalINS_6StringEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v820EscapableHandleScopeC1EPNS_7IsolateE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v89Signature3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v811HandleScopeD1Ev: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v86String9WriteUtf8EPciPii: symbol not found
Error relocating build/Release/zyre.node: _ZN2v87Isolate10GetCurrentEv: symbol not found
Error relocating build/Release/zyre.node: _ZN2v816FunctionTemplate12SetClassNameENS_5LocalINS_6StringEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN3zmq7dgram_tC1EPNS_5ctx_tEji: symbol not found
Error relocating build/Release/zyre.node: _ZN4node6Buffer4DataEN2v85LocalINS1_6ObjectEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v86Number3NewEPNS_7IsolateEd: symbol not found
Error relocating build/Release/zyre.node: _ZN2v816FunctionTemplate17PrototypeTemplateEv: symbol not found
Error relocating build/Release/zyre.node: _ZN2v82V813DisposeGlobalEPPNS_8internal6ObjectE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v86Object20SlowGetInternalFieldEi: symbol not found
Error relocating build/Release/zyre.node: _ZN2v86Object3SetENS_5LocalINS_7ContextEEENS1_INS_5ValueEEES5_: symbol not found
Error relocating build/Release/zyre.node: _ZN4node6Buffer4CopyEPN2v87IsolateEPKcm: symbol not found
Error relocating build/Release/zyre.node: _ZN2v811HandleScope12CreateHandleEPNS_8internal10HeapObjectEPNS1_6ObjectE: symbol not found
Error relocating build/Release/zyre.node: _ZN4node6Buffer6LengthEN2v85LocalINS1_6ObjectEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v87Isolate14ThrowExceptionENS_5LocalINS_5ValueEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v87Isolate17GetCurrentContextEv: symbol not found
Error relocating build/Release/zyre.node: _ZN2v86Object16SetInternalFieldEiNS_5LocalINS_5ValueEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN3zmq9scatter_tC1EPNS_5ctx_tEji: symbol not found
Error relocating build/Release/zyre.node: _ZN2v86String11NewFromUtf8EPNS_7IsolateEPKcNS_13NewStringTypeEi: symbol not found
Error relocating build/Release/zyre.node: _ZN3zmq8gather_tC1EPNS_5ctx_tEji: symbol not found
Error relocating build/Release/zyre.node: _ZN2v82V817FromJustIsNothingEv: symbol not found
Error relocating build/Release/zyre.node: _ZN2v814ObjectTemplate3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v85Value11Uint32ValueENS_5LocalINS_7ContextEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v82V812ToLocalEmptyEv: symbol not found
Error relocating build/Release/zyre.node: node_module_register: symbol not found
Error relocating build/Release/zyre.node: _ZN2v816FunctionTemplate16InstanceTemplateEv: symbol not found
Error relocating build/Release/zyre.node: _ZN2v86Object18InternalFieldCountEv: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v85Value8IsNumberEv: symbol not found
Error relocating build/Release/zyre.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v816FunctionTemplate11GetFunctionENS_5LocalINS_7ContextEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v82V89ClearWeakEPPNS_8internal6ObjectE: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v85Value12IntegerValueENS_5LocalINS_7ContextEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v811HandleScopeD2Ev: symbol not found
Error relocating build/Release/zyre.node: _ZN2v86Object32SetAlignedPointerInInternalFieldEiPv: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v85Value12BooleanValueENS_5LocalINS_7ContextEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v82V88MakeWeakEPPNS_8internal6ObjectEPvPFvRKNS_16WeakCallbackInfoIvEEENS_16WeakCallbackTypeE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v814ObjectTemplate11NewInstanceENS_5LocalINS_7ContextEEE: symbol not found
Error relocating build/Release/zyre.node: _ZN2v86Object38SlowGetAlignedPointerFromInternalFieldEi: symbol not found
Error relocating build/Release/zyre.node: _ZN2v88Template3SetENS_5LocalINS_4NameEEENS1_INS_4DataEEENS_17PropertyAttributeE: symbol not found
Error relocating build/Release/zyre.node: _ZNK2v85Value10Int32ValueENS_5LocalINS_7ContextEEE: symbol not found
```

[The container](https://github.com/weltraumco/tdrs-node/blob/feature/discovery/Dockerfile) should have every required library available, though.

**Comment by sappo** [comment]
Hi Marius,
I'm not quite sure that the node binding is in a usable state.

This is a quote from @hintjens from the mailing list:
> The actual code is in zproject. The Zyre binding that it generates now
is pretty nice, it's just missing the ability to pass CZMQ classes
(like zmsg), which is what I was adding, and where I got lost. The
NAN/C++ layers are over my head without days of concentration.

>So my open work was to get the CZMQ NodeJS binding working, at which
stage Zyre would be fully supported. (As well as Malamute and other
zproject client projects).

**Comment by mrusme** [comment]
Hey Kevin,

thank you for the quick reply & the insights! I understand the node binding might not be in a fully usable state - still I'm wondering why it performs pretty fine for my case when compiled/ran on my local Mac machine, while it complains when ran inside an Alpine Linux container. It appears to me that the node binding is trying to find a *zmq library but can't.

Also I'm wondering why the node binding actually clones czmq and libzmq for compiling itself, instead of using the system-wide installed versions?

Would be glad to help refactoring the node binding / building process, as soon as I got my head around this a bit better.

Thanks!

**Comment by sappo** [comment]
> thank you for the quick reply & the insights! I understand the node binding might not be in a fully usable state - still I'm wondering why it performs pretty fine for my case when compiled/ran on my local Mac machine, while it complains when ran inside an Alpine Linux container. It appears to me that the node binding is trying to find a *zmq library but can't.

Regarding the mac vs container weirdness I sadly cannot help as I never used the node binding before. Maybe our newly recruited node guys @lgeiger and @rgbkrk  can help you in that regard.

> Also I'm wondering why the node binding actually clones czmq and libzmq for compiling itself, instead of using the system-wide installed versions?

We do not use system-wide installed versions by convention. Furthermore we assume all dependencies are in the same root folder, where they are cloned to if they don't exist. Also we may require a build script from a depended library that is only available in the source code.

> Would be glad to help refactoring the node binding / building process, as soon as I got my head around this a bit better.

I cannot help you with node specifics but if you need help with zproject and code generation stuff feel free to contact me.

**Comment by rgbkrk** [comment]
I'm only slightly familiar with zyre from when @hintjens was tackling node in general for zproject onwards.

We ended up taking a different approach and modernizing the node zmq bindings to create [zeromq.js](https://github.com/zeromq/zeromq.js), which is _only_ wrapping libzmq. No zyre there. It does use your system-wide install if building from source, otherwise prebuilds are available which are much easier to digest cross platform.

One day I'd love to get back to the work Pieter kicked off for node + czmq + zproject.
