### ISSUE TITLE
Instruction for building with VS2015

### ISSUE THREAD

**Issue by XinyuHou** [zeromq/zyre#493]
The instructions in Readme doesn't work for VS2015. After run configure.bat, cd into vs2015 and run build,bat doesn't work neither. Open up the VS solution and added libczmq.lib directory get it compiled but not linked. 

> Severity	Code	Description	Project	File	Line
> Error	LNK2001	unresolved external symbol __imp_zframe_destroy	libzyre	C:\Projects\zyre\builds\msvc\vs2015\libzyre\zre_msg.obj	1

Please give more instructions about building on Windows

**Comment by sappo** [comment]
Hi @XinyuHou, thanks for reporting. Sadly I don't own a valid windows license so I'm not able to help you with specifics. What's the problem/error msg with the build.bat script?

**Comment by sappo** [comment]
You can try to port the msvc build script from libzmq to zyre (https://github.com/zeromq/libzmq/tree/master/builds/msvc) they should be similar in most regards.

**Comment by sappo** [comment]
You can have a look at the libzmq msvc build system as this is working properly (https://github.com/zeromq/libzmq/tree/master/builds/msvc).

**Comment by XinyuHou** [comment]
@sappo 
Thanks for your reply.

When I ran the build.bat in VS2015, I got some error like "invalid configuration in solution"

I manually open and configure the solution in VS2015. What got me was I didn't realize I needed to add some preprocessor in the project configuration. Here is the stuff I added:

ZMQ_STATIC;CZMQ_STATIC;ZYRE_STATIC;
