### ISSUE TITLE
Add encryption and authentication to peers

### ISSUE THREAD

**Issue by interpretor** [zeromq/zyre#494]
I would like to add encryption and authentication to the peers.
It is already mentioned in the 36/ZRE draft under the paragraph "Security".
As zyre uses czmq, I would do it similar to the example in ironhouse.c and save the certs of all peers in the cert storage.
Any advice from your side?

**Comment by wesyoung** [comment]
this is how we were starting to think about it at the python level:

https://github.com/zeromq/pyre/issues/94

@hintjens laid out some examples but i've not had a chance to implement yet, but have started to think about with these points in mind...

**Comment by wesyoung** [comment]
i think this can be closed?

https://github.com/zeromq/zyre/pull/550
https://github.com/zeromq/zyre/pull/556

**Comment by bluca** [comment]
Yes - thanks!
