### ISSUE TITLE
Will there be another Zyre release?

### ISSUE THREAD

**Issue by hasan-igl** [zeromq/zyre#507]
Hi,

We are looking at using Zyre in a new project. But we are wondering, why there are no new releases? and if there is intention for new releases in the future?

Thanks
Hasan

**Comment by sappo** [comment]
@bluca I don't see any obstacles for doing a release of zyre. Do you?

**Comment by bluca** [comment]
It went from 1.2.0 to 0.0.4, do you know what happened there? 

Also there are API changes I think, so it needs a soname bump probably, need to have a look with abidump

**Comment by sappo** [comment]
I think it was a mistake by Pieter and nobody noticed.

**Comment by sappo** [comment]
Zyre has no stable API yet but promoting it to stable is something we have to do for the next release. Thus bumping the ABI is required.

**Comment by bluca** [comment]
Then I think if we use a version greater than 1.2.0 for the next one we'll be fine, as that's greater than 0.0.4 anyway.

I can have a poke around ABI dumper later tonight

**Comment by sappo** [comment]
That would be great. I'll take care of the API promotion to stable.

**Comment by bluca** [comment]
You already did with https://github.com/zeromq/zyre/commit/a2c9f17c318b872a683fa22f27686f59aaa86ce6 :-)

**Comment by bluca** [comment]
But it could benefit a second review to make really sure it's all good to go, I'll have another look myself

**Comment by bluca** [comment]
API seems fine as-is to me, but I'm not (yet) a very heavy Zyre user. Does it look good to you?

Also indeed API is not compatible with previous version. I'd like to follow semver and bump to 2.0.0. Does this sounds good for you?

**Comment by sappo** [comment]
Everything looks fine. A bump to version 2 sounds good.

Am 14.01.2017 22:50 schrieb "Luca Boccassi" <notifications@github.com>:

**Comment by bluca** [comment]
I'll send an email to the mailing list asking if anyone has a comment on the API, and if there's no answer we can go ahead. I'll say the deadline is Tuesday night GMT so there's enough time for people who use it at work.

**Comment by bluca** [comment]
The NEWS file is completely blank. I'll start from what changed since the previously tagged version, and then see if I can fill in the gaps going backwards

**Comment by bluca** [comment]
I haven't forgot :-) Will finish the NEWS at the latest by the weekend

**Comment by bluca** [comment]
I think we are all set, so I'll finalize the changelog and push the tag

**Comment by sappo** [comment]
Yeah!

Am 20.01.2017 20:16 schrieb "Luca Boccassi" <notifications@github.com>:

**Comment by bluca** [comment]
All done! https://github.com/zeromq/zyre/releases/tag/v2.0.0
