### ISSUE TITLE
Problem with IPv6 and link-local addresses

### ISSUE THREAD

**Issue by jimklimov** [zeromq/zyre#518]
As discussed with @bluca during the hackathon, the recent addition of IPv6 support does not fully work.

One problem is that different OSes have slightly different semantics for `getaddrinfo()` and similar routines - e.g. that they do or do not add the `%zoneid` to an IPv6 address (e.g. the `%wlan0` string), which is required on link-local addresses. As a result, the initial implementation can blindly use two zoneids, adding one to the string it gets from the system.

Another problem is that (it seems) somewhere between sending a HELLO message with the (sender's!) `%zoneid` and using it as an endpoint of the remote counteragent on the other side, the string occasionally gets mangled. I am not sure yet where or how, but it feels that somewhere it may be processed with printf-like routines that take the percent-sign before zoneid name as an escape character.

Things we tried to address include chopping off the original (remote) zoneid as it does not make sense for local OS'es interface names anyway, and perhaps replacing that with an egress local interface name, if one can be predefined and bolted on (e.g. must be for link-local?) which worked with moderate success and complexity - but did not culminate in having everything "just work" always and reliably so far.

Finally, and especially important for such mangling and interpretation of address strings, is the issue of separating the last component of (colon-separated) IPv6 address that might be 4 digits with no port number in the string, from an address with a colon-separated port as well. Proper solution for this would be to support "IP literals" where the numeric IP address (with `%zoneid` if present) is enclosed in square brackets, maybe for both IPv6 and IPv4 to be consistent (this notation was introduced for IPv4, for cases where one wants the dot-separated numbers to mean precisely the IP address and not maybe the chain of all-numeric DNS domain names). For the timeslot during hackathon it proved a bit too complex to implement this carefully - but IMHO this is the way forward, and the solution may impact (or will need to get implemented similarly) in a number of ZMQ-related projects. Perhaps the logic for string manipulation of IPv4 and IPv6 addresses should become part of libzmq and get called from there by all interested parties layered above the same foundation.

**Comment by bluca** [comment]
Yes there's work to do with link-local indeed, I will give it a shot again during the next weekend if no one beats me to it

**Comment by bluca** [comment]
@jimklimov sorry for the delay. Had some time to work on this again.
When you have time, could you please try again once https://github.com/zeromq/czmq/pull/1667 is also merged?

**Comment by bluca** [comment]
@jimklimov did you have any chance to give this a test?
