### ISSUE TITLE
Zyre hangs on burst of USRSIG1 signals

### ISSUE THREAD

**Issue by mschuckmann** [zeromq/zyre#522]
I've got a problem where my Zyre based applications hangs under a heavy load of USRSIG1 signals. 

I'm still debugging but it appears that at least 2 things are going on. 

1. The zbeacon thread exits early, there is a break in the while loop that can occur if -1 is returned returned by zmq_poll(). It seems like it should at least check if errno is set to EINTR and continue instead of breaking. 

2. The zpoller code seems to be setup to terminate when when any number of functions return with EINTR returned. There is the zpoller_set_nonstop() function that appears to change this behavior but it is marked as draft and the comments around it don't exactly make sense to me so I'm not sure if I should use it. I'm also not sure if my application even has access to the zpoller's that are terminating early. 

I'm wondering if there are bug(s) here or if I'm missing something.

**Comment by bluca** [comment]
Note that zpoller_set_nonstop is no longer draft, it's been declared stable in 4.0

The problem with using that (as you correctly guessed the zpoller is an internal object so it would need to be set in zyre) and to stop returning on EINTR is that correctly terminating becomes more tricky. If you manage to patch czmq and zyre to work correctly with those changes then please send us PRs

**Comment by mschuckmann** [comment]
@bluca  Thank you for the information, I will submit a patch if I can get it working correctly. 
I did a little research and I think I could use sigevent() with SIGEV_THREAD for my notification needs (kernel driver notifying user app of interrupts) and avoid this problem. Either way it would be good to get this working correctly and contribute to the library. 

Should I post my question to czmq to see if anyone else has any input on the proper fix?

**Comment by bluca** [comment]
The same folks follow both repositories so I don't think it's necessary, and the change has to be done in zyre anyway so I think this is the right place.
The change itself would be pretty easy I think - just call zpoller_set_nonstop in the zyre_node_new() function.

There's a few programs in the repo you can use to test it, zpinger and ztester_beacon, they are built together with the library.
