### ISSUE TITLE
Assert without headers on a peer

### ISSUE THREAD

**Issue by Schoonology** [zeromq/zyre#523]
I'm writing a much-simplified implementation of ZMTP/ZRE/Zyre to run on embedded hardware, and decided to leave off the ZRE headers on the client. Unfortunately, this triggered an assertion during `zyre_node_recv_peer`:

```
W: 17-03-02 17:51:37 zre_msg: GET_LONGSTR failed
Assertion failed: (self), function zhash_pack, file src/zhash.c, line 669.
```

I fixed the issue locally with [this commit](https://github.com/Schoonology/zyre/commit/ac17d210868b90562733c1a50c5df54c0cab13c7), but I'm far from sure this is the best solution.

1. Have you seen this issue before?
2. Is this the right solution?
3. Can I provide more information to help?

**Comment by sappo** [comment]
Hi Michael,

that is neat!

Regarding your issue, it should work fine if you send an empty 
dictionary according to the RFC (https://rfc.zeromq.org/spec:36/ZRE).

BR
//Kevin

**Comment by bluca** [comment]
If the spec allows it then it's fine to check before derefencing. Could you please send a PR to fix it?

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/zyre/pull/525
