### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by DRTEK** [zeromq/zyre#526]
hello 
is it possible to set uuid at runtime ?
thanks

**Comment by bluca** [comment]
No as it's used to identify a peer by all other nodes, so it would become a bit messy. What's your use case?

**Comment by DRTEK** [comment]
i have central database holds peers ,i could use the name as identifier however i wanted to see if it was doable .

**Comment by sappo** [comment]
You could set a custom identifier in the headers which are provided by each
ENTER messages.

Am 11.03.2017 22:28 schrieb "MK" <notifications@github.com>:

**Comment by DRTEK** [comment]
yes i think it is right way to go 
thanks

**Comment by bluca** [comment]
Cool. Closing now since it's solved.

**Comment by wesyoung** [comment]
fwiw, i've tried something like this in the past- the lesson learned? don't try to track uuid's. it just gets messy. we ended up using the HEADER for something like that. seemed to work ok. we augmented it a little with a local routing table in the peer that held node names (which i think may have been overkill, but we were learning the framework and messing around a bit).

**Comment by sappo** [comment]
@DRTEK not sure if this helps in your case, but zyre allows you to set the public name of its node. Which is the first 6 characters of the uuid by default. The problem was that the API call to set this name (`set_name()`) was not exposed in the header file until now. 

PR #527 fixes this!

**Comment by DRTEK** [comment]
sure it does 👍 thank you very much .. 
if i may i have one more question (sorry i do not know where to ask questions about the library )
*  is it okay to pass the zactor_t as an argument to different threads so main and another thread can send messages to the thread ? (please see below)

	zactor_t *cluster_actor = zactor_new(createnode, clusternode);

	zactor_t *wireless_actor = zactor_new(startwilo, cluster_actor);
thanks alot

**Comment by bluca** [comment]
no, actors (and zmq sockets) must not be passed among threads

**Comment by DRTEK** [comment]
can you point me to  two way communication sample between threads ? please

**Comment by bluca** [comment]
a zmq socket of type ZMQ_PAIR and endpoint inproc://
