### ISSUE TITLE
Messages lost on (temporary) connection reset

### ISSUE THREAD

**Issue by alt-** [zeromq/zyre#529]
The readme mentions that Zyre does reliable messaging, but internal tests on Windows with perf_local and perf_remote (post pr #528, master branch) with max_node=1 and max_message=100000 find a sequence number error (zyre_peer.c:424) happens whenever the TCP connection resets. 

The connection reset is triggered by physically pulling the ethernet cable between two machines to simulate a bad cable or WiFi dropout.  Zyre occasionally recovers, but even a <5s disconnect (expiry time  30s) may cause the OS to terminate both ends of the TCP connection with WSAECONNRESET, in which case the sequence error removes the peer and allows it to re-enter without any resends.

Zeromq handles this by reconnecting (zmq::stream_engine_t::in_event -> error (connection_error) -> session->engine_error (reason) -> zmq::session_base_t::reconnect), but does not appear to resend what has been pushed to the OS' network send buffer. The zeromq guide has various patterns for reliable messaging (http://zguide.zeromq.org/php:chapter4), but zyre doesn't appear to use any of them. 

Is this expected?

**Comment by alt-** [comment]
Any comments or discussions are welcome. We're deciding whether we should fork the project to quickly implement reliable messaging or try to work it into the mainline.

I can see arguments both for having reliable messaging, which might add latency due to resends, and semi-reliable, with early outs so the application level can handle disconnects.

**Comment by sappo** [comment]
Hi @alt-,
I'm a bit wary that this kind of reliability may introduces a lot of overhead especially for peer to peer networks.

Nevertheless we welcome any contributions that follow our guidelines. I imagine that your change will require to adjust the ZRE protocol (https://rfc.zeromq.org/spec:36/ZRE/). In that case you will need to create a new draft RFC of the ZRE protocol with your proposed changes. If you require more information feel free to ask.

I'll be looking forward to your solution :)
