### ISSUE TITLE
Problem: zyre lacks security

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/zyre#533]
At the moment, anyone can impersonate a peer as he likes.
This could be solved by increasing the UUID size to 32 octets so it could be the public key of a curve key pair.
What do you think?

**Comment by bluca** [comment]
I think the proper solution is to add full curve support: https://github.com/zeromq/zyre/issues/494

**Comment by Asmod4n** [comment]
Ops, didn't see that.
Closed via #494

**Comment by wesyoung** [comment]
i see the uuid as more like the MAC address (eg: arp). in addition to adding curve to the sockets, the easier work-around right now is probably just adding messaging signing to your application stack(?).

**Comment by Asmod4n** [comment]
@wesyoung 
I am currently only using zyre to find peers to connect to which are in the same group, i am not using zyre to send messages.
I am doing messaging with another set of sockets, which is authenticated and encrypted.

I would like to do the same with zyre alone, or else i could just reimplement the UDP broadcast messages without a need to link my app to czmq and zyre, which is a bit complicated when you want to cross compile.
