### ISSUE TITLE
infinite loop of enter/exit using gossip

### ISSUE THREAD

**Issue by bbdb68** [zeromq/zyre#542]
runing this code 

```
#include <assert.h>
#include <stdlib.h>
#include <zyre.h>

int main ()
{
    int rc;

    zyre_t* node1 = zyre_new("node1");  
    zyre_set_verbose(node1);
    zyre_gossip_bind(node1, "tcp://*:7778");


    zyre_t* node2 = zyre_new("node2");
    zyre_set_verbose(node2);
    zyre_gossip_connect(node2, "tcp://127.0.0.1:7778");

    rc = zyre_start(node1);
    assert(rc == 0);
    rc = zyre_start(node2);
    assert(rc == 0);

    zmq_sleep(3);

    zyre_stop(node1);
    zyre_destroy(&node1);
    zyre_stop(node2);
    zyre_destroy(&node2);
    return 0;
}
```

usually works (each node receives one ENTER event), but it often runs into a loop of enter/exit events, making the application unsusable.

seen on windows. Using inproc, the issue does not occur (neither with udp discovery)

**Comment by bluca** [comment]
(edited the code so that it can be copy&pasted and compiled without changes)

I've ran this a few times on Linux (Debian 9 with latest libzmq/czmq/zyre from git) and can't seem to reproduce unfortunately

**Comment by bbdb68** [comment]
@bluca thanks for looking. On my computer (windows), it fails about every 10 runs.

**Comment by bluca** [comment]
Ran 30 times in a row and it still works. Sorry but I'm really not familiar with Windows, maybe somebody else can help. The only thing I can suggest is to attach a debugger when it gets stuck and try to inspect the state.

**Comment by bbdb68** [comment]
here is the log of a failling case, may be it can help

D: 17-08-24 15:23:20 node1:     API command=BIND
D: 17-08-24 15:23:20 node1:     API command=PUBLISH
D: 17-08-24 15:23:21 node2:     API command=CONNECT
D: 17-08-24 15:23:22    555:node1                            : start:
D: 17-08-24 15:23:22    555:node1                            :     HELLO
D: 17-08-24 15:23:22    555:node1                            :         $ get first tuple
D: 17-08-24 15:23:22    555:node1                            :         > have tuple
D: 17-08-24 15:23:22    555:node1                            : have tuple:
D: 17-08-24 15:23:22    555:node1                            :     ok
D: 17-08-24 15:23:22    555:node1                            :         $ send PUBLISH
D: 17-08-24 15:23:22    555:node1                            :         $ get next tuple
D: 17-08-24 15:23:22    555:node1                            :         > have tuple
D: 17-08-24 15:23:22    555:node1                            : have tuple:
D: 17-08-24 15:23:22    555:node1                            :     finished
D: 17-08-24 15:23:22    555:node1                            :         > connected
D: 17-08-24 15:23:22 node2:     API command=PUBLISH
D: 17-08-24 15:23:22    555:node1                            : connected:
D: 17-08-24 15:23:22    555:node1                            :     PUBLISH
D: 17-08-24 15:23:22    555:node1                            :         $ store tuple if new
D: 17-08-24 15:23:22    555:node1                            : connected:
D: 17-08-24 15:23:22    555:node1                            :     forward
D: 17-08-24 15:23:22    555:node1                            :         $ get tuple to forward
D: 17-08-24 15:23:22    555:node1                            :         $ send PUBLISH
D: 17-08-24 15:23:22    555:node1                            :         > connected
D: 17-08-24 15:23:22    555:node1                            :         > connected
D: 17-08-24 15:23:22    555:node1                            : connected:
D: 17-08-24 15:23:22    555:node1                            :     PUBLISH
D: 17-08-24 15:23:22    555:node1                            :         $ store tuple if new
D: 17-08-24 15:23:22    555:node1                            :         > connected
I: 17-08-24 15:23:22 (node1) connect to peer: endpoint=tcp://127.0.0.1:49160
I: 17-08-24 15:23:22 (node1) send HELLO to peer=- sequence=1
I: 17-08-24 15:23:22 (node2) connect to peer: endpoint=tcp://127.0.0.1:49159
I: 17-08-24 15:23:22 (node2) send HELLO to peer=- sequence=1
I: 17-08-24 15:23:22 (node1) peer expired name= endpoint=tcp://127.0.0.1:49160
I: 17-08-24 15:23:22 (node1) EXIT name= endpoint=tcp://127.0.0.1:49160
I: 17-08-24 15:23:22 (node2) recv HELLO from peer=- sequence=1
I: 17-08-24 15:23:22 (node2) ENTER name=node1 endpoint=tcp://127.0.0.1:49159
I: 17-08-24 15:23:23 (node1) connect to peer: endpoint=tcp://127.0.0.1:49160
I: 17-08-24 15:23:23 (node1) send HELLO to peer=- sequence=1
I: 17-08-24 15:23:23 (node1) recv HELLO from peer=- sequence=1
I: 17-08-24 15:23:23 (node1) ENTER name=node2 endpoint=tcp://127.0.0.1:49160
I: 17-08-24 15:23:23 (node2) EXIT name=node1 endpoint=tcp://127.0.0.1:49159
I: 17-08-24 15:23:23 (node2) connect to peer: endpoint=tcp://127.0.0.1:49159
I: 17-08-24 15:23:23 (node2) send HELLO to peer=- sequence=1
I: 17-08-24 15:23:23 (node2) recv HELLO from peer=- sequence=1
I: 17-08-24 15:23:23 (node2) ENTER name=node1 endpoint=tcp://127.0.0.1:49159
I: 17-08-24 15:23:23 (node1) EXIT name=node2 endpoint=tcp://127.0.0.1:49160
I: 17-08-24 15:23:23 (node1) connect to peer: endpoint=tcp://127.0.0.1:49160
I: 17-08-24 15:23:23 (node1) send HELLO to peer=- sequence=1
I: 17-08-24 15:23:23 (node1) recv HELLO from peer=- sequence=1

**Comment by bbdb68** [comment]
look at the code, the errors occurs when a peer is early detected as expired. I also noticed than when a peer is created  (zyre_peer_new), its evasive_at and expired_at values are set to 0, which means that the peer is already expired.

although I did not find the root cause, what do you think about calling zyre_peer_refresh from zyre_peer_new, so that initial value of expired_at/evasive_are meaningful ?

**Comment by bluca** [comment]
It's already done after creating the peer:

https://github.com/zeromq/zyre/blob/master/src/zyre_node.c#L573
https://github.com/zeromq/zyre/blob/master/src/zyre_node.c#L611

**Comment by bbdb68** [comment]
ok, but what I see is peer->expire_at is 0 whithin zyre_node_ping_peer.
Maybe call zyre_peer_refresh  earlier just after the new ?

**Comment by bluca** [comment]
It's strange because it should be in the same thread - IE zyre_node_ping_peer shouldn't fire off before that function that creates the peer returns, when it will have called _refresh.

But please do try it out and if it solves your problem then send a PR for it

**Comment by bbdb68** [comment]
ok my mistake! I am in fact running zyre version 2.0.0, and there is no call to refresh in this version

It has been added since : 
https://github.com/zeromq/zyre/commit/398678b6c9d22dce71ee31f1e183233bea7f62d5
and applying this commit to the 2.0.0 source seems to fix my issue

Sorry I should I have checked earlier. closing

**Comment by bluca** [comment]
Great, thanks for confirming it's fixed
