### ISSUE TITLE
redefining print() is a Python 2 syntax error

### ISSUE THREAD

**Issue by cclauss** [zeromq/zyre#545]
$ __python2 -c "def print(x): pass"__ # Syntax Error__

__Problem:__ The current code tries to redefine `print()` twice which will be a Python 2 Syntax Error.

flake8 testing of https://github.com/zeromq/zyre on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./bindings/python_cffi/zyre/Zyre.py:243:13: E999 SyntaxError: invalid syntax
    def print(self):
            ^

./bindings/python_cffi/zyre/ZyreEvent.py:91:13: E999 SyntaxError: invalid syntax
    def print(self):
            ^
```

**Comment by bluca** [comment]
It's generated from the zyre print API: https://github.com/zeromq/zyre/blob/master/api/zyre.api#L223
which cannot be renamed as it's a stable API - we have the same problem with Java: https://github.com/zeromq/zproject/issues/947 I guess what we need  is a generic way for bindings to list the reserved keywords and automatically rename them, so that there's a common pattern

**Comment by twhittock** [comment]
In the ctypes binding, I believe we import print function from future.
Perhaps the same should be done in the cffi binding.

**Comment by bluca** [comment]
Doesn't help unfortunately:

```
[  169s] Compiling /home/abuild/rpmbuild/BUILDROOT/zyre-1.2.0+git20170904-26.1.x86_64/usr/lib64/python2.7/site-packages/zyre_cffi/Zyre.py ...
[  169s]   File "/usr/lib64/python2.7/site-packages/zyre_cffi/Zyre.py", line 244
[  169s]     def print(self):
[  169s]             ^
[  169s] SyntaxError: invalid syntax
[  169s] 
[  169s] Compiling /home/abuild/rpmbuild/BUILDROOT/zyre-1.2.0+git20170904-26.1.x86_64/usr/lib64/python2.7/site-packages/zyre_cffi/ZyreEvent.py ...
[  169s]   File "/usr/lib64/python2.7/site-packages/zyre_cffi/ZyreEvent.py", line 92
[  169s]     def print(self):
[  169s]             ^
[  169s] SyntaxError: invalid syntax
```

I think the problem is that a zyre function is called ```print``` rather than the lack of import.

**Comment by sappo** [comment]
I'll take care of it later today.

Am 04.09.2017 12:18 schrieb "Luca Boccassi" <notifications@github.com>:

**Comment by bluca** [comment]
Thanks!
