### ISSUE TITLE
Memory leak in zyre_node_recv_beacon( ) when it returns half way.

### ISSUE THREAD

**Issue by mike-zhou** [zeromq/zyre#575]
In function void zyre_node_recv_beacon( ) in file zyre_node.c, memory is not freed when this function returns in half way:

whether frame is empty is not checked before the return at line 1098.

memory allocated to ipaddress is not freed before the "return" at the following line:
- 1110
- 1119
- 1127

I think that code can be modified as:
--------------------------------------------------------------
static void
zyre_node_recv_beacon (zyre_node_t *self)
{
    //  Get IP address and beacon of peer
    char *ipaddress = zstr_recv (self->beacon);
    zframe_t *frame = zframe_recv (self->beacon);
    if (ipaddress == NULL) {

        // add this line to free memory allocated at beginning of this function.
        if(frame != NULL)
            zframe_destroy(&frame);

        return;                 //  Interrupted
    }
    ......
#ifdef ZYRE_BUILD_DRAFT_API
    if (beacon.version != self->beacon_version) {
        if (self->verbose)
            zsys_debug ("tossing beacon, version mis-match");

        // add this line to free memory allocated at beginning of this function.
        zstr_free(&ipaddress);

        return;
    }

//     beacon missing public key when we're in secure mode
    if (self->secret_key && (beacon.public_key[0] == 0)) {
        //         toss it to avoid down-grade attacks
        if (self->verbose)
            zsys_debug ("tossing beacon to avoid security downgrade, does not contain public key...");

        // add this line to free memory allocated at beginning of this function.
        zstr_free(&ipaddress);

        return;
    }

#else
    if (beacon.version != BEACON_VERSION) {
        if (self->verbose)
            zsys_debug ("tossing beacon");

        // add this line to free memory allocated at beginning of this function.
        zstr_free(&ipaddress);

        return;                 //  Garbage beacon, ignore it
    }
#endif

......

**Comment by bluca** [comment]
Could you please send a PR?

**Comment by mike-zhou** [comment]
#576 
This pull request #576 is to fix Memory leak in zyre_node_recv_beacon( ) when it returns half way
