### ISSUE TITLE
zyre_peer_t private 

### ISSUE THREAD

**Issue by gkarsai** [zeromq/zyre#579]
It seems zyre_peer_t is a private type. When zyre_peers(zyre_t*) is called the result cannot be parsed as the elements are just void* and thus cannot be coerced into zyre_peer_t*.

**Comment by sthoduka** [comment]
zyre_peers returns a zlist_t *

Here is a snippet that should work:

```
    zlist_t * peers = zyre_peers(node);
    int size = zlist_size(peers);
    for (int i = 0; i < size; i++)
    {
        char * peer_uuid = (char*)zlist_pop(peers);
        // do something with peer_uuid
        free(peer_uuid);
    }
    zlist_destroy(&peers);
```

**Comment by bluca** [comment]
Yes, it's a list of strings (the UUID of the peers). zyre_peer is an internal class and it's intentionally not exposed. Closing.
