### ISSUE TITLE
RFC number when encryption is enabled

### ISSUE THREAD

**Issue by odessa2** [zeromq/zyre#580]
I am currently writing a technical document and I need to know the RFC number when using zyre with encryption. The length of the UDP beacon matches RFC43, is this the correct RFC? In my understanding, this is an extension to RFC36 (the one mentioned in this repo).

Can someone confirm or refute my elaboration?

**Comment by bluca** [comment]
Yes with encryption enabled it's https://rfc.zeromq.org/spec:43/ZRE
Note that it's still DRAFT and as such subject to change in backward incompatible ways without any prior notification

**Comment by odessa2** [comment]
Thank you! Closing the issue.
