### ISSUE TITLE
Problem: API inputs are not checked for validity

### ISSUE THREAD

**Issue by gabm** [zeromq/zyre#583]
I noticed that calling `zyre_leave(node, nullptr)` crashes the `zyre_api_recv_api` function. Of course it doesnt make sense to do that but it crashes "somewhere internally" because my userinput is not checked before calling the zyre api. I'd expect to get an error "Hey, you are trying to do something weird". Probably this affects other functions as well.

On the other hand I'm not sure whether such checks are meant to be done by the zyre api?

**Comment by sappo** [comment]
We usually assert parameters for nullpointers. Could you send a PR with the
fix. Thanks!

gabm <notifications@github.com> schrieb am Fr., 18. Mai 2018 15:53:

**Comment by gabm** [comment]
@sappo done
