### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by loydjayme25** [zeromq/zyre#590]
Good day, about the enhancement of the project. I am willing to submit my design for logo and icon.

**Comment by sappo** [comment]
Absolutely, you're welcome to :)

**Comment by loydjayme25** [comment]
@sappo Greetings !

pls do suggest or comments about the design.

![proposals](https://user-images.githubusercontent.com/37318022/41332507-bf72143c-6f10-11e8-8b5b-82c354f420b6.png)

**Comment by sphaero** [comment]
Nice, I really like it's simplicity. Its design is catchy and very usable in a lot of contexts. To add suggestions; It's not very readable. That doesn't have to be a problem but then why not play more with the typography? Did you make it not square on purpose? It sort of looks square but also doesn't. I'm not sure why. So if it was me I would play more with lines of the logo. I.e. The 'Z' has slanted edges but only at the start of it. I would also just upper- or lowercase the texts. Also Zyre is a peer to peer framework this might be a hint to try to catch visually as well?

**Comment by loydjayme25** [comment]
the box itself is a square, and i think i better change the font and you are right, ill use the lowercase texts.

**Comment by loydjayme25** [comment]
@sphaero is this fine ?

![1](https://user-images.githubusercontent.com/37318022/41340357-b5cfe184-6f29-11e8-9d3f-327f3978caf2.png)

**Comment by sappo** [comment]
@loydjayme25 neat :) I do like to first one with all upper cases better. The slanted edged in the second one at the end of the Z is a nice touch though. Maybe we can have a web of interconnected dots or circles to refer to the peer to peer nature of zyre.

**Comment by loydjayme25** [comment]
I will add your suggestion sir @sappo , lemme make some changes for awhile.

**Comment by loydjayme25** [comment]
Is this what you mean sir @sappo  ?

![2](https://user-images.githubusercontent.com/37318022/41345378-ffed7874-6f35-11e8-8873-87fd0ff834e2.png)

**Comment by loydjayme25** [comment]
@sphaero yes, i will remove the dots and slant the edges. sounds good :D

**Comment by loydjayme25** [comment]
@sphaero 

![3](https://user-images.githubusercontent.com/37318022/41389484-b5ab7a7a-6fc3-11e8-9bce-06eca428ed9d.png)

**Comment by loydjayme25** [comment]
![4](https://user-images.githubusercontent.com/37318022/41389607-57c2fc5c-6fc4-11e8-85f2-33907420d50f.png)

**Comment by sappo** [comment]
Great job :+1: I like the grey square one best

**Comment by sappo** [comment]
The following formats would be great:
* png as 32x32, 64x64, 128x128, 256x256, 512x512
* svg

**Comment by loydjayme25** [comment]
can i have your email sir @sappo ?

**Comment by sappo** [comment]
mail@kevinsapper.de

Loyd Jayme <notifications@github.com> schrieb am Do., 14. Juni 2018 14:51:

**Comment by loydjayme25** [comment]
sir @sappo  is there any emails because i cant email you using the mail you have given.

**Comment by loydjayme25** [comment]
i can make a PR also

**Comment by sappo** [comment]
I think that would be best, simply put it in a logo folder. Please don't
forget your copyright and license statement. Thanks.

Loyd Jayme <notifications@github.com> schrieb am Fr., 15. Juni 2018 07:56:

**Comment by bluca** [comment]
SVG is better for git storage - what should the license be? Given MPL2 doesn't cover trademarks, perhaps CC-BY-4.0?

**Comment by sappo** [comment]
Yes, CC-BY-4.0 is fine

Luca Boccassi <notifications@github.com> schrieb am Fr., 15. Juni 2018
21:56:

**Comment by loydjayme25** [comment]
Maybe ill just drop the designs [here](https://drive.google.com/open?id=1dtvuO0poIJemO3T8fJ7HtlCEDxrU4HEa) .. so you can adjust where to put those things, all files are there including Ai, SVG, JPG, and PNG.

**Comment by loydjayme25** [comment]
Thank you so much everyone for the help ! i really appreciate it, i am very sorry for a late reply because i was busy on my studies.

**Comment by sphaero** [comment]
I'm reopening this as we never quite finished this which is shame for such nice work. Are source files still available somewhere @loydjayme25? The google link is dead.

**Comment by sailaja-nagireddy** [comment]
Attached the reconstructed logos as [logos.zip](https://github.com/zeromq/zyre/files/5643946/logos.zip) in the `png` format.  If there is interest generating `svg` can be investigated.

**Comment by bluca** [comment]
svg would be better for committing to git, yes

**Comment by sailaja-nagireddy** [comment]
[Here](https://github.com/zeromq/zyre/files/5682125/zyre-logo-grey.svg.zip) is the svg version of the above image.  With this I hope we can close this issue.

**Comment by sphaero** [comment]
I created a PR. I also cleaned up the svg as it had quite some artefacts. You probably used a tracer :wink: @sailaja-nagireddy 

See #683

**Comment by sailaja-nagireddy** [comment]
Yes I did use `Inkspace's` trace bitmap functionality to generate the svg image.  Thank you for the clean-up and the pr.  Is the clean-up an automated process or you re-drew the image as `svg`?

**Comment by sphaero** [comment]
It's manual work, I aligned all the vertices and removed the unnecessary ones. Also removed all the beziers and weird shapes :smile:
