### ISSUE TITLE
More Detailed Documentation and examples

### ISSUE THREAD

**Issue by sotiris-oikonomou** [zeromq/zyre#591]
Are there any examples covering more possible usages of the zyre protocol and also is there a more detailed documentation?

**Comment by keent** [comment]
There's an example here: 
https://github.com/zeromq/zyre/blob/master/examples/chat/chat.c

The possibilities are endless. If you have to synchronize different types of client apps, servers apps, databases, services, PCs, embedded devices, then zyre will be handy.

Looking at the API, the usage should be straightforward:

ENTER fromnode name headers ipaddress:port
    a new peer has entered the network
EVASIVE fromnode name
    a peer is being evasive (quiet for too long)
EXIT fromnode name
    a peer has left the network
JOIN fromnode name groupname
    a peer has joined a specific group
LEAVE fromnode name groupname
    a peer has joined a specific group
WHISPER fromnode name message
    a peer has sent this node a message
SHOUT fromnode name groupname message
    a peer has sent one of our groups a message

**Comment by keent** [comment]
If ever you came up / can open source a usage. Feel free :)

**Comment by bluca** [comment]
glard uses zyre: https://github.com/ZMQers/glar150
