### ISSUE TITLE
In Debian GNU/Linux 9.4 (stretch) you get symbol lookup error: /usr/local/lib/libczmq.so.4: undefined symbol: zmq_poller_new

### ISSUE THREAD

**Issue by sotiris-oikonomou** [zeromq/zyre#592]
Following the installation instruction on the README.md of the master branch, at the end when you try to run zyre_selftest and zpinger you get symbol lookup error: /usr/local/lib/libczmq.so.4: undefined symbol: zmq_poller_new. The problem here is that debian has libsodium18 preinstalled and this get priority in linking even if you compile and install libsodium from the repository.
One solution is to uninstall the preinstalled libsodium and install from the git repository.

**Comment by bluca** [comment]
This is not related to libsodium, nor zyre. Those are symbols from libzmq.

What's likely happening is that you built CZMQ locally (usr/local path) with DRAFT APIs but are using libzmq from the system without DRAFTs.

Just remove any locally built libsodium/libzmq/libczmq and use the libraries from the system, with ```apt install libczmq-dev libzmq3-dev```
