### ISSUE TITLE
Test failed on Linux 18.04

### ISSUE THREAD

**Issue by leochan2009** [zeromq/zyre#608]
Hi,

I built the zyre against czmq.so.4.0.2 and libzmp.so.4.2.2 under Linux 18.04, and run the zyre_selftest, however, the test failed. here is the output error message:

* zyre_event: I: 18-10-05 11:13:07 (node1) JOIN group=GLOBAL
D: 18-10-05 11:13:07 node2:     API command=CONNECT
I: 18-10-05 11:13:07 (node2) JOIN group=GLOBAL
D: 18-10-05 11:13:07 node2:     API command=PUBLISH
I: 18-10-05 11:13:07 (node2) connect to peer: endpoint=tcp://neptune:49152
I: 18-10-05 11:13:07 (node2) send HELLO to peer=- sequence=1
I: 18-10-05 11:13:07 (node1) connect to peer: endpoint=tcp://neptune:49153
I: 18-10-05 11:13:07 (node1) send HELLO to peer=- sequence=1
I: 18-10-05 11:13:08 (node1) peer expired name= endpoint=tcp://neptune:49153
I: 18-10-05 11:13:08 (node1) EXIT name= endpoint=tcp://neptune:49153
I: 18-10-05 11:13:08 (node2) peer expired name= endpoint=tcp://neptune:49152
I: 18-10-05 11:13:08 (node2) EXIT name= endpoint=tcp://neptune:49152
zyre_selftest: /home/user/Desktop/Work/framework-build/ThirdParty/zyre-2.0.0/src/zyre_event.c:312: zyre_event_test: Assertion `streq (zyre_event_type (event), "ENTER")' failed.

When i debug into the code and found the event was "Exit" instead of "ENTER", that is why the streq failed.
Thanks in advance!

Best,
Chen

**Comment by bluca** [comment]
You don't need to build it, you can add our OBS repository for Ubuntu 18.04 and get the packages instead:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-stable&package=libzyre-dev

**Comment by leochan2009** [comment]
Hi, 
Thanks for the reply.  Unfortunately i will need a local build from our server. The library was built without error and all the API works as expected. It is weird that tests all failing...
Do you know why the local build test failed. it seems like the peer is expired:
 18-10-05 11:13:08 (node1) peer expired name= endpoint=tcp://neptune:49153
It is interesting that tests all passed in the the travis CI build.The travis CI is using ubuntu 14.04 and gcc of version 4.8. i am using gcc 7.3. maybe that is the difference? 
Thanks,
Chen
