### ISSUE TITLE
how to add -fPIC CPPFLAG when make

### ISSUE THREAD

**Issue by mozeat-sun** [zeromq/zyre#609]
hi
   i need to add CPPFLAG -fPIC when build libzmq，should i modify the ../libzmq/build/Makefile "CXXFLAGS = -g -O2 -Wno-tautological-constant-compare -fPIC"

**Comment by sphaero** [comment]
what if you run
```
make CXXFLAGS = '-g -O2 -Wno-tautological-constant-compare -fPIC'
```

**Comment by andy5995** [comment]
@mozeat-sun , I would try

```CXXFLAGS="-g -O2 -Wno-tautological-constant-compare -fPIC" ./configure```

All on one line. Then run `make clean && make` That would affect everything that's built though, not just libzmq.
