### ISSUE TITLE
Zyre problem when system IP address changes

### ISSUE THREAD

**Issue by mschuckmann** [zeromq/zyre#614]
I'm chasing down a problem that occurs when the IP address of the interface my zyre node is bound to is changed. The IP address change occurs due to a IPv4 Link Local address conflict when another system joins the network and is using the same Link local address. The Link Local protocol correctly detects the conflict and one of the nodes changes it's address (within the same subnet) but Zyre ends up being very confused, it's so bad that even a new node started after the change on a different system sees nodes that were created before the change but can't communicate with them.

The problem (or at least part of the problem) seems to be that the hostname (i.e. address) that is sent in the HELLO message is determined when the node is created and then never updated (it's right about here in the code: 
https://github.com/zeromq/zyre/blob/5be61ad196a187a0eca7d82c1574b02467ddfa34/src/zyre_node.c#L1418 in the code. 

Peer nodes get really confused because when they receive zbeacon pings they get the new address from the udp receive but they don't or are unable to reconnect. I think this is partly because the HELLO message still includes the old address.

So my question is has this type of issue been seen/discussed before? 
Is there a good solution within zyre, czmq or do I have have to have my client code monitor for local ip address changes, tear down the zyre node and create a new node (I'm a bit concerned about doing this as it will be quite disruptive).

**Comment by sphaero** [comment]
Yes, we've seen it before. In Pyre as well. It's not that hard to fix but then again there are probably more cases where this goes wrong and probably more problems will arise. Basically it means bringing zbeacon and zyre_node sockets down and reconstruct them.
