### ISSUE TITLE
zyre-android-2.0.0 not working on Android 4.1

### ISSUE THREAD

**Issue by thealmikey** [zeromq/zyre#628]
I have jeromq version 0.4.3 as a dependency in my build.gradle and have zyre-android-2.0.0.jar in the /libs directory. The setup works well for android 6.0 and android 7.1 but i get this error on an Samsung-GTS7262 device which has android 4.12
```     
...
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1891]:  
  87 could not load needed library 'libzmq.so' for
 'libzyrejni.so' (load_library[1093]: Library 'libzmq.so' not found)
```
The only idea i have is ABI compatibility with the zyre-android jar file. I cloned the repo and tried to build zyre-android on my windows 10 machine following the instructions in the build page but have been getting getting this error 
```
+ export ANDROID_API_LEVEL=android-16
+ ANDROID_API_LEVEL=android-16
+ export 'ANDROID_SYS_ROOT=C:\android-sdk\ndk-bundle/platforms/android-16/arch-arm'
+ ANDROID_SYS_ROOT='C:\android-sdk\ndk-bundle/platforms/android-16/arch-arm'
+ '[' '' = -d ']'
+ source ../../../builds/android/android_build_helper.sh
++ '[' -z '' ']'
++++ dirname ../../../builds/android/android_build_helper.sh
+++ cd ../../../builds/android
+++ pwd
++ ANDROID_BUILD_DIR=/c/Users/ALMIKEY/Desktop/zyre-master/builds/android
++ ANDROID_BUILD_FAIL=()
+ android_build_env
+ '[' -z 'C:\android-sdk\ndk-bundle' ']'
+ '[' -z 'C:\Program Files\Android\android-ndk-r12b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin' ']'
+ '[' -z arm-linux-androideabi-4.9 ']'
+ '[' -z arm-linux-androideabi ']'
+ '[' -z arm ']'
+ android_build_check_fail
+ '[' '!' 0 -eq 0 ']'
+ '[' '!' -d 'C:\android-sdk\ndk-bundle' ']'
+ '[' '!' -d 'C:\Program Files\Android\android-ndk-r12b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin' ']'
+ ANDROID_BUILD_SYSROOT='C:\android-sdk\ndk-bundle/platforms/android-16/arch-arm'
+ '[' '!' -d 'C:\android-sdk\ndk-bundle/platforms/android-16/arch-arm' ']'
+ ANDROID_BUILD_PREFIX=/c/Users/ALMIKEY/Desktop/zyre-master/builds/android/prefix/arm-linux-androideabi-4.9
+ mkdir -p /c/Users/ALMIKEY/Desktop/zyre-master/builds/android/prefix/arm-linux-androideabi-4.9
+ android_build_check_fail
+ '[' '!' 0 -eq 0 ']'
+ echo '********  Building zyre Android native libraries'
********  Building zyre Android native libraries
+ cd ../../../builds/android
+ ./build.sh
Building czmq in /c/Users/ALMIKEY/Desktop/czmq...
Building libzmq in /c/Users/ALMIKEY/Desktop/libzmq...
make: *** No rule to make target `clean'.  Stop.
Can't locate Autom4te/ChannelDefs.pm in @INC (you may need to install the Autom4te::ChannelDefs module) (@INC contains: C:/PROGRA~2/GnuWin32/autoconf/share/autoconf /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /c/Program Files (x86)/GnuWin32/bin/autoreconf line 42.
BEGIN failed--compilation aborted at /c/Program Files (x86)/GnuWin32/bin/autoreconf line 42.
autogen.sh: error: autoreconf exited with status 0
```
I managed to tweak the values for ANDROID_BUILD_SYSROOT and Api level to 16, as that's what i have in the NDK, i don't know much about C builds or even whether i could actually make an zyre-android ABI compatible for the Android 4.1 i was targeting.

**Comment by bluca** [comment]
jeromq is not a dependency of zyre, as it's a native java implementation. As the readme says, you'll need libzmq and czmq which are C++/C libraries.

**Comment by thealmikey** [comment]
In an android project that uses jeromq, would i still need to add libzmq and czmq as native C++/C libraries in order to use zyre?

**Comment by bluca** [comment]
Yes.
There' an alternative implementation that can use jeromq but I have never used it: https://github.com/zeromq/jyre

**Comment by thealmikey** [comment]
Thank you very much :smile: That was super fast, let me check it out and see if it helps resolve my issue.
Also wanted to ask if i'm wrong about the whole ABI thing, is the compiled zyre-android.jar in the release specific to some abis or could it be a wholly different thing making things work on android versions 6 and 7 but not 4.1?

**Comment by bluca** [comment]
I'm afraid I'm not really familiar with the NDK and its workings, so I don't know. @sappo any idea?
