### ISSUE TITLE
Zyre 2.0.0 dosn't pass CMake (on windows)

### ISSUE THREAD

**Issue by eninyo** [zeromq/zyre#629]
the latest release version fails on CMAke with the following: (x64 with VS2017)
```
fatal: not a git repository (or any of the parent directories): .git

git workspace root [128]: 
CMake Error at CMakeLists.txt:39 (if):
  if given arguments:

    "128" "==" "0"

  Unknown arguments specified

  Configuring incomplete, errors occurred!
```
the latest master version pass the CMake.

**Comment by eninyo** [comment]
the problem was that i download the version and not clone it.
i didn't have the ".git" directory so it fails.
when i clone it (and got the git dir) everything works fine.

**Comment by bluca** [comment]
That was a bug in the cmake file which has since been fixed in master by commit https://github.com/zeromq/zyre/commit/936d1c05c9b5dbe807df9fc3bcc02aea246c0d38
