### ISSUE TITLE
Build Zyre with ndk r19c

### ISSUE THREAD

**Issue by raphaelcfernandes** [zeromq/zyre#631]
How should I build Zyre for the newer version of ndk? I get the following error:

Android build failed for the following reasons:
  The CPP binary does not exist or is not executable
    /home/raphael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-cpp
  The CC binary does not exist or is not executable
    /home/raphael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
  The CXX binary does not exist or is not executable
    /home/raphael/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++

How should I replace these files?

**Comment by bluca** [comment]
the embedded scripts support r11, if you want something different you'll have to use it with autotools as a normal cross compilation toolchain

**Comment by raphaelcfernandes** [comment]
Is there any instructions out there for it?

**Comment by bluca** [comment]
https://developer.android.com/ndk/guides/other_build_systems#autoconf

**Comment by raphaelcfernandes** [comment]
So, I've been working on building Zyre with NDK 19rc. I think I could work out some old dependencies and at the end I could built zyre with the newest NDK. However, when I try to execute the app I get "java.lang.UnsatisfiedLinkError: dlopen failed: library "libgnustl_shared.so" not found", do you have any idea/guidance on how to solve it? After solving it, I'm pretty sure it will run the app, and I can do a pull request with the modifications. Thanks!

**Comment by sappo** [comment]
libgnustl is no longer supported as part of the latest NDK. You should try to use `android-ndk-r19c/sources/cxx-stl/llvm-libc++/` instead. Hence you got it to compile you probably already do. But you seem to link to `-lgnustl_shared` somewhere in the process. Do you have your progress commited somewhere?

**Comment by raphaelcfernandes** [comment]
I fixed the problem. Zyre is been built with NDK19 and is running in my app correctly. I need to clean up some stuff and I will be able to do a pull request

**Comment by sappo** [comment]
This is awesome!

I'm really excited to see your changes :)

Raphael Cardoso Fernandes <notifications@github.com> schrieb am Mo., 3.
Juni 2019, 18:16:

**Comment by raphaelcfernandes** [comment]
It's been a while but I finally had the time to push into my branch before any further PR. I was using the scripts from bindings/jni/android to build the projects, however, I wanted to make it more general by generating SOs for different ABIs in Android Studio. Here is the link: https://github.com/raphaelcfernandes/Zyre-Android inside zyre-aar is where things happen. The projects (libzmq, czmq, zyre) are added as submodules. First, the generateJniHeaders.sh should be executed then just build the project (zyre-aar) and the SOs will be generated for each ABI (armv7a, arm64, x86 and x86_64), but I just have the armv7a in the abiFilter to make the build process faster.

However, when I try to import my AAR to my app I get: couldn't find 'libuuid.so'. Am I doing something wrong or forgetting anything in my CMakeLists.txt in the root folder? I really appreciate any help!

**Comment by raphaelcfernandes** [comment]
I found the problem. CZMQ branch should be latest_release and not master. Then it builds correctly and the aar gives no error.

**Comment by sappo** [comment]
It should build with latest master as well.

I know why the libuuid error occurs and will try to fix it tomorrow.

Raphael Cardoso Fernandes <notifications@github.com> schrieb am Fr., 21.
Juni 2019, 22:05:

**Comment by sappo** [comment]
This is still on my agenda.

**Comment by raphaelcfernandes** [comment]
Please, feel free to use my CMakeLists and modify it as you need (https://github.com/raphaelcfernandes/Zyre-Android). If any modification was made please let me know so I can check what I was possibly doing wrong. Also, it would be very nice to add libsodium + curvezmq to it (my future plan).

**Comment by sappo** [comment]
Thanks, I will.

Raphael Cardoso Fernandes <notifications@github.com> schrieb am Fr., 11.
Okt. 2019, 17:35:

**Comment by BenjaminDeroche** [comment]
Hello @sappo 

I was working on updating the Android build scripts so they work with latest version of the NDK toolchain (see [libzmq](https://github.com/BenjaminDeroche/libzmq/commit/ca0d5a8bf27f3c1e5e4478f201478e4947b22b50) & [czmq](https://github.com/BenjaminDeroche/czmq/commit/535f9f784206c2bceaa09772e1b869e3eb2e5021) changes) before I noticed your ongoing work.

It is compiling but still need some improvements (code clean up, build for all archs, rewrite this in zproject_android.gsl ...)

Is it worth to pursue, according to your plans to rewrite the Java and Android build process ?

**Comment by sappo** [comment]
Hi @BenjaminDeroche

Yes, absolutely! Go for it  :+1: 

I just finished my work on restructuring the JNI binding so we can publish jars which include the native libs for win, macos and linux. The android part I kept as is but moved it into a subproject.

**Comment by BenjaminDeroche** [comment]
It finally work with NDK r20, see zeromq/zproject#1210 ! :tada: 

I didn't check your changes yet .. and I still have a few questions:
- May I add a few QOL improvements to run this scripts outside of Docker/Travis ? For example, we don't necessary need to re-download the NDK every time in this context.
- Do you plan to replace make by cmake for android build scripts ? Since android binding build scripts already use it.
- One last note, I think there is something fundamentally wrong with the way we cross compile for Android and I couldn't find how to fix it. If you enable the verbose mode of make, you will see that compiling and linking steps both includes multiple invalid paths which are added automatically. I think this could be avoided by making a better use of sysroot and pkgconfig

**Comment by sappo** [comment]
Neat :)

* Yes!!!
* No plan currently, but feel free to do so.
* If you can fix this with a better solution - go for it!

**Comment by benjdero** [comment]
It seems that my changes break the build of the jni bindings but I don't know why, can you take a look @sappo ?

**Comment by sappo** [comment]
Sure I'll have a look at it.

Benjamin Deroche <notifications@github.com> schrieb am Di., 29. Okt. 2019,
10:28:
