### ISSUE TITLE
zeromq.tools does not exist in master branch

### ISSUE THREAD

**Issue by raphaelcfernandes** [zeromq/zyre#633]
gradle build jar can't file the path utilityClasses 'src/main/java/org/zeromq/tools/ZmqNativeLoader.java'. There was a commit two days ago but this class was not included.

**Comment by bluca** [comment]
@sappo any idea what could be the issue?

**Comment by sappo** [comment]
@bluca I probably forgot to commit a newly generated file. Could you please regenerate from zproject and check if you got time. Otherwise I'll do it tomorrow.

**Comment by sappo** [comment]
@raphaelcfernandes the latest version of the bindings will automatically package the required C binaries into the jar and load them if they are not present on the system. Currently works only for Linux though.

**Comment by sappo** [comment]
@bluca I also missed to to check in the new file for czmq.

**Comment by bluca** [comment]
I tried regenerating in czmq, but git status --ignored doesn't show anything new in bindings/jni

**Comment by sappo** [comment]
There should be a new folder bindings/jni/src/main/java/org/zeromq/tools

Luca Boccassi <notifications@github.com> schrieb am Fr., 31. Mai 2019,
17:57:

**Comment by bluca** [comment]
Ah, it was already checked in czmq - opened a pr
