### ISSUE TITLE
How to send/receive bytes with zmsg

### ISSUE THREAD

**Issue by raphaelcfernandes** [zeromq/zyre#638]
I'm trying to receive bytes[] from my zmsg but I'm always getting Core Dumped after instantiate Zframe, is there a correct way to send/receive bytes[] from an image bitmap using zmsg? Sorry if this is the wrong place, if there is any wiki page/forum please let me know and I'll post there.

**Comment by sappo** [comment]
Hi Raphael,

I'm happy to help.
Is it possible to for you to share your code please.

Cheers
Kevin

Raphael Cardoso Fernandes <notifications@github.com> schrieb am Di., 16.
Juli 2019, 23:30:

**Comment by raphaelcfernandes** [comment]
Sure thing.

This is how I send the msg:

sender.java:
```
public void sendMessage(String uuid) {
        ByteBuffer bf = onImageCapturedEvent.getByteBuffer();
        Size size = onImageCapturedEvent.getSize();
        Zmsg msg = new Zmsg();
        Bitmap bitmap = BitmapUtilities.byteBufferToBitmap(bf, size);
        final byte[] compressedBytes = BitmapUtilities.compressBitmap(bitmap);
        msg.addmem(compressedBytes,compressedBytes.length);
        this.zyre.whisper(uuid, msg);
}
```
receiver.java:
```
public receiver() {
       ...
        byte[] byteArr = msgToReceive.pop().data();
       ...
}
```

But I get the following error:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff6a5fcbf3a, pid=5512, tid=5544
#
# JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM (11.0.3+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x9f3a]  check_match+0xa
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /home/raphael/Documents/zyrejni-chat-linux/core.5512)
#
# An error report file with more information is saved as:
# /home/raphael/Documents/zyrejni-chat-linux/hs_err_pid5512.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

**Comment by sappo** [comment]
Are you using the latest zyre master?

**Comment by raphaelcfernandes** [comment]
That was exactly the problem. I was using a build on Linux that was giving this error, however using my Android build with the last CMake + latest zyre worked perfectly! I will close the issue. Thank you.

**Comment by sappo** [comment]
Okay great I think we have to create a new release with those bug fixes in
the library loading.

Raphael Cardoso Fernandes <notifications@github.com> schrieb am Mi., 17.
Juli 2019, 16:56:
