### ISSUE TITLE
iOS build

### ISSUE THREAD

**Issue by ameykshirsagar** [zeromq/zyre#641]
How can I build and iOS shared lib of Zyre??

**Comment by sappo** [comment]
I'm afraid nobody has tried or at least documented the how to. But we're
grateful if someone would contribute it.

Amey Kshirsagar <notifications@github.com> schrieb am Mo., 5. Aug. 2019,
01:04:

**Comment by sappo** [comment]
I don't have an iOS device but maybe this is helpful to you:
https://medium.com/swift-and-ios-writing/using-a-c-library-inside-a-swift-framework-d041d7b701d9

**Comment by stvales** [comment]
iOS generally relies on static libraries and frameworks but dynamic libraries have been enabled for some time now. In any case, or zyre to work, you'll also need to compile zeromq and czmq (and possibly sodium). It is possible to do so using cross compilation from macOS. If you want to distribute your app on the app store, you'll need to be carefull with signing and sandboxing. This means that the cross-compiled libraries need to be properly signed as well if they are dynamic and embedded with your app.
I would recommend that you use static libraries in any case. It makes signing process easier.

Then, if you are using swift, you'll need to wrap zyre (and possibly czmq). No additional work though if you are using Objective-C.
