### ISSUE TITLE
Ping mechanism generates an EVASIVE event every 5 seconds and should not

### ISSUE THREAD

**Issue by stvales** [zeromq/zyre#642]
Every five seconds, the test on evasive timeout in zyre_node.c/zyre_node_ping_peer is always true because no ping has been sent every time zyre_node_ping_peer is called, as it should be the case. Ping is currently sent in zyre_node_ping_peer  only if evasive timeout has been reached and no other mechanism sends pings.

Attached patch makes zyre_node_ping_peer send ping all the time, including when evasive timeout is reached, but not when expired timeout is reached (i.e. when peer is removed).

[patch.txt](https://github.com/zeromq/zyre/files/3586698/patch.txt)

**Comment by medons** [comment]
The call to zyre_node_ping_peer in the zyre_node_actor really serves to "test" whether the peer is still alive or not.  The function zyre_node_ping_peer really should be called zyre_node_test_peer or something like that.  I don't think calling ping every time is the right thing.  I think it works better as it is implemented, only pinging if the peer seems to be evasive.

**Comment by stvales** [comment]
@medons yes you are right. Discussion has progressed in pull requests section. See #643.
I'm closing this issue as its formulation is not relevant anymore.
