### ISSUE TITLE
System.AccessViolationException when destroy instance

### ISSUE THREAD

**Issue by NitecoOPS** [zeromq/zyre#646]
On Windows, after call destroy method then you will get exception:

> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Steps to reproduce:
1. Create instance: zyre_new(name)
2. Do something like
+ zyre_start(self)
+ zyre_stop(self)
3. Destroy instance: zyre_destroy(self)

**Comment by sthoduka** [comment]
try sleeping for a short while (100ms with zclock_sleep) after zyre_stop before zyre_destroy

**Comment by NitecoOPS** [comment]
Thank for your answer but its still there :(

**Comment by sthoduka** [comment]
can you post a code snippet?

**Comment by NitecoOPS** [comment]
Hi sthoduka,
Below is my code:
1. Build zyre dll with vcpkg:
vcpkg install zyre:x64-windows --head
Then we have: 
+ libczmq.dll
+ libzmq-mt-4_3_3.dll
+ libzyre.dll
2. Create console application with binding:
[DllImport(@"ExternalLibs\libzyre.dll")]
public static unsafe extern long zyre_new(string name);

[DllImport(@"ExternalLibs\libzyre.dll")]
public static unsafe extern int zyre_start(long self);

[DllImport(@"ExternalLibs\libzyre.dll")]
public static unsafe extern void zyre_destroy(long self_p);

[DllImport(@"ExternalLibs\libzyre.dll")]
public static unsafe extern void zyre_stop(long self);
...

class Program
    {
        static void Main(string[] args)
        {
            var znode = new Zyre("RunSelfTest");
            znode.SetHeader("X-Hello", "World");
            znode.Start();
            znode.Stop();
            ZClock.Sleep(100);
            znode.Dispose();
        }
    }

**Comment by NitecoOPS** [comment]
Run console app then we got:
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at zyre_destroy(Int64 self_p)

**Comment by sthoduka** [comment]
unfortunately I cannot reproduce the exception, so I'm not sure where to look. Sorry.

**Comment by NitecoOPS** [comment]
Thank sthoduka,
I resolved this by change signature on destroy method:
**Original**:
ZYRE_EXPORT void
    zyre_destroy (zyre_t **self_p);

**Before**:
[DllImport(@"ExternalLibs\libzyre.dll")]
        public static unsafe extern void zyre_destroy(long self_p);

**After**
[DllImport(@"ExternalLibs\libzyre.dll")]
        public static unsafe extern void zyre_destroy(ref long self_p);
