### ISSUE TITLE
zyre_shouts return code

### ISSUE THREAD

**Issue by smalls12** [zeromq/zyre#651]
Looking at the `zyre.h` API, `zyre_shouts` returns an integer (see below):

`int zyre_shouts (zyre_t *self, const char *group, const char *format, ...)`

However, looking at the code, in all cases, the return code is always `0`.

Should this be just made void?

**Comment by smalls12** [comment]
I went down the rabbit hole of zyre ---> czmq ---> libzmq, the return codes could be propagated up from below but might actually require work down at libzmq.

(zyre) `zyre_shouts`
(czmq) `zstr_sendm / zstr_send`
(czmq) `s_send_string`
(libzmq) `zmq_sendmsg`
(libzmq) `zmq_msg_send`
(libzmq) `s_sendmsg` ***

*** does some form of truncating the return code

This could give the user to check the return code within zyre.

**Comment by keent** [comment]
well you could raise the issue with libzmq/czmq and issue a patch there.
then zyre lastly.

**Comment by smalls12** [comment]
I can make any corresponding issues with libzmq/czmq, but that is only required should a meaningful return code be desired from `zyre_shouts`.

**Comment by smalls12** [comment]
Resolved by #654

I ended up only making a change to `zyre.c` as the current implementations in czmq seemed sufficient.
