### ISSUE TITLE
New zyre instances created after previous Ctrl-C will hang in zyre_name()

### ISSUE THREAD

**Issue by jesseoff** [zeromq/zyre#653]
When using zyre with a zpoller until zpoller_terminated() detects Ctrl-C, the very next new zyre instance hangs in zyre_name() at the zstr_sendx() call.

Strangely enough, preceding the call to the zyre_name() is a zyre_uuid() call that succeeds and returns, but returns a zero length string for the UUID.

The problem goes away if I zsys_shutdown() before instantiating a new zyre with zyre_new().

Also, while zyre_name() is hung, each further Ctrl-C advances and unblocks until the very next zyre call.

**Comment by sphaero** [comment]
Do you have a code snippet that demonstrates this? Would be helpful to reproduce

**Comment by jesseoff** [comment]
I'm using a [Lisp system for Zyre](https://github.com/jesseoff/cl-zyre) but I'll see I can reduce this to C over the weekend.  Specifically, I'm playing with the applications "tock-server" and "tock-client" defined in [tock.lisp](https://github.com/jesseoff/cl-zyre/blob/master/tock.lisp) of the above project and hitting them with Ctrl-C's in the REPL.
