### ISSUE TITLE
Java bindings generation fail

### ISSUE THREAD

**Issue by benjdero** [zeromq/zyre#663]
Hi @sappo 

On latest versions of Czmq & Zyre, I fail to generate Java bindings. When I run the `build.sh` script from `czmq-jni/android`, it fail on the `initCMake` task.

```
> Task :czmq-jni:initCMake FAILED
-- Checking for module 'libzmq'
--   No package 'libzmq' found
-- Could NOT find LIBZMQ (missing: LIBZMQ_LIBRARIES LIBZMQ_INCLUDE_DIRS) 
CMake Error at CMakeLists.txt:28 (message):
  libzmq not found.
```

Did I miss something ?

**Comment by sappo** [comment]
You need to checkout libzmq into the same directory as czmq and zyre.

**Comment by benjdero** [comment]
I already have libzmq, czmq and zyre cloned within the same directory.

**Comment by sappo** [comment]
Have a look at `bindings/jni/ci_build.sh`. I think you'll need to have libzmq installed.
I'll fix the README as soon as possible.

**Comment by sappo** [comment]
Have a look at `bindings/jni/ci_build.sh`. I think you'll need to have libzmq installed.
I'll fix the README as soon as possible.
