### ISSUE TITLE
Why examples can not work 

### ISSUE THREAD

**Issue by herobigdata2099** [zeromq/zyre#666]
I compile and install lastest version on centos 7.4.Chat and mininal  examples  can not work.I'd like to known what wrong with me.

**Comment by sphaero** [comment]
You really need to provide more info. We cannot help you like this. What version of zyre, czmq, libzmq etc are you using. Are there any errors?

**Comment by herobigdata2099** [comment]
I use lastest version of zyre,czmq and libzmq from github. I start two chat program under examples  and input "hello world" ,I cannot receive anything.

**Comment by sthoduka** [comment]
Can you try running two instances of `zpinger --verbose` and show the output? That might give some clues.

**Comment by herobigdata2099** [comment]
first instance：
I: 20-05-16 09:51:37 Create Zyre node, uuid=34F30049A095793B6CE988D4B26BAC39, name=34F300
D: 20-05-16 09:51:37 34F300:     API command=START
I: 20-05-16 09:51:37 zbeacon: API command=CONFIGURE
I: 20-05-16 09:51:37 zbeacon: interface=eth0 address=192.168.1.217 broadcast=192.168.1.255
I: 20-05-16 09:51:37 zbeacon: configured, hostname=192.168.1.217
D: 20-05-16 09:51:37 34F300:     API command=JOIN
I: 20-05-16 09:51:37 zbeacon: API command=PUBLISH
I: 20-05-16 09:51:37 (34F300) JOIN group=GLOBAL
D: 20-05-16 09:51:37 34F300:     API command=DUMP
I: 20-05-16 09:51:37 zyre_node: dump state
I: 20-05-16 09:51:37  - name=34F300 uuid=34F30049A095793B6CE988D4B26BAC39
I: 20-05-16 09:51:37  - endpoint=tcp://192.168.1.217:49152
I: 20-05-16 09:51:37  - discovery=beacon port=5670 interval=0
I: 20-05-16 09:51:37  - headers=0:
I: 20-05-16 09:51:37  - peers=0:
I: 20-05-16 09:51:37  - own groups=1:
I: 20-05-16 09:51:37    - GLOBAL
I: 20-05-16 09:51:37 zbeacon: API command=SUBSCRIBE
I: 20-05-16 09:51:37  - peer groups=0:


second instance:
I: 20-05-16 09:52:28 Create Zyre node, uuid=8CEB91E65B195AA8A92DB6E120740326, name=8CEB91
D: 20-05-16 09:52:28 8CEB91:     API command=START
I: 20-05-16 09:52:28 zbeacon: API command=CONFIGURE
I: 20-05-16 09:52:28 zbeacon: interface=eth0 address=192.168.1.217 broadcast=192.168.1.255
I: 20-05-16 09:52:28 zbeacon: configured, hostname=192.168.1.217
D: 20-05-16 09:52:28 8CEB91:     API command=JOIN
I: 20-05-16 09:52:28 zbeacon: API command=PUBLISH
I: 20-05-16 09:52:28 (8CEB91) JOIN group=GLOBAL
D: 20-05-16 09:52:28 8CEB91:     API command=DUMP
I: 20-05-16 09:52:28 zyre_node: dump state
I: 20-05-16 09:52:28  - name=8CEB91 uuid=8CEB91E65B195AA8A92DB6E120740326
I: 20-05-16 09:52:28  - endpoint=tcp://192.168.1.217:49153
I: 20-05-16 09:52:28  - discovery=beacon port=5670 interval=0
I: 20-05-16 09:52:28 zbeacon: API command=SUBSCRIBE
I: 20-05-16 09:52:28  - headers=0:
I: 20-05-16 09:52:28  - peers=0:
I: 20-05-16 09:52:28  - own groups=1:
I: 20-05-16 09:52:28    - GLOBAL
I: 20-05-16 09:52:28  - peer groups=0:

**Comment by sthoduka** [comment]
it looks like peer discovery is not working for some reason. Do you have a firewall enabled? You might need to allow udp traffic on port 5670

**Comment by herobigdata2099** [comment]
Yes,you are right.It worked after I close firewall.I'd like to know how to get conclusion of my information.
