### ISSUE TITLE
Unable to build zyre-jni

### ISSUE THREAD

**Issue by BJWielink** [zeromq/zyre#667]
After installing and building Zyre I am unable to build zyre-jni through Gradle. Gradle will give the following error:

```
Build file '/home/<username>/zyre_build/zyre/bindings/jni/zyre-jni/build.gradle' line: 25

A problem occurred evaluating project ':zyre-jni'.
> Could not resolve all files for configuration ':zyre-jni:runtime'.
   > Could not find any matches for org.zeromq.czmq:czmq-jni:latest.integration as no versions of org.zeromq.czmq:czmq-jni are available.
     Searched in the following locations:
       - file:/home/<username>/.m2/repository/org/zeromq/czmq/czmq-jni/
       - https://repo.maven.apache.org/maven2/org/zeromq/czmq/czmq-jni/maven-metadata.xml
       - https://jcenter.bintray.com/org/zeromq/czmq/czmq-jni/maven-metadata.xml
     Required by:
         project :zyre-jni
```

I tried a lot of things, but I am not sure how I can get it to build properly.
I installed Zyre and it's dependencies using the build guide shown at README.md in the root of the Zyre project.

**Comment by sappo** [comment]
You'll need to build and install the czmq-jni bindings first.

You can follow the ci steps:

https://github.com/zeromq/zyre/blob/master/bindings/jni/ci_build.sh

Bert Jan Wielink <notifications@github.com> schrieb am Do., 11. Juni 2020,
09:17:

**Comment by BJWielink** [comment]
Thank you very much! After I executed the .sh file I was indeed able to build it.
