### ISSUE TITLE
JNI src/zsys.c: error

### ISSUE THREAD

**Issue by Riddle-C** [zeromq/zyre#668]
After building the latest Zyre-JNI and CZMQ from GithHub I created a new project that linked to the native libraries and the java library. I am however receiving the following error with the most basic project one could imagine:

```
java: src/zsys.c:221: zsys_init: Assertion `!s_process_ctx' failed.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
The code I have written is just:

```
fun main() {
    val node = Zyre("zyre_test")
    node.start()
}
```

**Comment by sappo** [comment]
I've tried this a while ago: https://github.com/sappo/zyrejni-example

I'll have time on Sunday to look into the error.

Am Do., 11. Juni 2020 um 16:40 Uhr schrieb Riddle-C <
notifications@github.com>:

**Comment by sappo** [comment]
The error occurs because your program immediately terminates after calling `node.start()`. You need to keep it alive.
