### ISSUE TITLE
Will there be another Zyre release? (2)

### ISSUE THREAD

**Issue by newr5** [zeromq/zyre#669]
Dear developers,
A couple of years ago someone submitted an issue (#507) with the same title, and a new release was made as a result of that.
Do you think that there have been enough changes with respect to version 2.0.0 that they might also result in a new version?
Thank you for your efforts.

Regards,
Vincent

**Comment by sappo** [comment]
Is there a new feature you require that is not supported with the current
release?


newr5 <notifications@github.com> schrieb am Fr., 19. Juni 2020, 15:55:

**Comment by newr5** [comment]
Hi, thanks for your reply.

I must admit that I didn't look into all 311 commits that were made since release 2.0.0.
It's not new features that I am looking for, but I thought that there must have been some bugs fixed, and it would be great if those fixes appeared in an 'officially endorsed', stable release.

I am currently in the process of upgrading software to use the latest stable zeromq (4.3.2), czmq (4.2.0) releases, and would have liked to have used a more recent 'official' zyre release as well.
I know that I can clone the git repository to have the most recent Zyre code, but in order to have a reproducible installation, I would rather use release tarballs.

Thanks again for your time,
Vincent

**Comment by ged** [comment]
Version 2.0.0 doesn't expose `zyre_set_name` which I'd like to make use of, so I too would like a new release. Thanks for all your work on this!

**Comment by ged** [comment]
I still would appreciate a new release if possible.

I am planning on using Zyre in a new system and I would feel much better about being able to pin it to a released version. Is there anything I or someone else can do to help with making a new release?

**Comment by sphaero** [comment]
You could start by drafting the release notes (changelog) if you want to help

**Comment by ged** [comment]
Okay, great idea, thanks!

**Comment by stephan57160** [comment]
It will be like 4 years that 2.0.0 was set ...
We would appreciate a new release too, at least a tag 2.0.1.

**Comment by sappo** [comment]
I'll create a new release next week.

Stephan Guilloux <notifications@github.com> schrieb am So., 17. Jan. 2021,
15:52:

**Comment by stephan57160** [comment]
Thx a lot

**Comment by ged** [comment]
Thanks so much for the new release! Leader election is amazing.
