### ISSUE TITLE
Curve messages dropped on Windows 10

### ISSUE THREAD

**Issue by dekel2003** [zeromq/zyre#671]
I have started using Zyre with curve and noticed the following issue:
I run 2 instances of **_zpinger -c -v_**
zbeacon discovery works fine and create the zyre_peer object.
Every instance sends messages (HELLO, PING) but never receive any message.

It happens only on Zyre compiled as **Release** on Windows 10.
The zpinger works fine on Debug, and on my Linux machine.

I've tried to compile the libraries with different versions of libsodium, and without libsodium but it didn't help.

finally I've noticed an issue with the following lines in the code (both in zyre_peer.c and zyre_node.c):
```
        assert (zmq_z85_decode (pub, self->public_key));
        assert (zmq_z85_decode (sec, self->secret_key));
        zcert_t *cert = zcert_new_from(pub, sec);
```
I checked the public key of the **cert** by _zcert_public_txt(cert)_  and found wrong result.

I changed the conversion to use zarmour object as following:

```
            // zarmour use for string conversion
        zarmour_t *armour = zarmour_new ();
        zarmour_set_mode (armour, ZARMOUR_MODE_Z85);
        zarmour_set_pad (armour, false);
        zarmour_set_line_breaks (armour, false);

          // convert keys from Z85 strings (40 bytes) to raw byte arrays (32 bytes)
        zchunk_t *decoded_public_key =
          zarmour_decode (armour, self->public_key);
        zchunk_t *decoded_secret_key =
          zarmour_decode (armour, self->secret_key);

          // create zcert from the decoded keys
        zcert_t *cert = zcert_new_from (zchunk_data (decoded_public_key),
                                        zchunk_data (decoded_secret_key));

..........
        zcert_destroy (&cert);
        zchunk_destroy (&decoded_secret_key);
        zchunk_destroy (&decoded_public_key);
        zarmour_destroy (&armour);
```

And now it works fine. tested with zpinger.exe
I can submit pull request if there isn't better solution.

**Comment by sphaero** [comment]
Are you saying it works fine without curve? I'm not really familiar with the curve option in Zyre. But you can submit a pull request, we can then wait what the CI tests will give us. If it's fine we'll merge.

**Comment by bluca** [comment]
What version are you using?

There was a problem with release builds, typically on windows, breaking asserts - this was fixed recently: https://github.com/zeromq/zyre/commit/2e1b24537b866
If you have an older version without that fix, it would explain it

**Comment by dekel2003** [comment]
@bluca 
Problem reproduced on latest master commit. (I updated the library after it wasn't working with older commit).
on 2 different Windows 10 computers.
compiled with MSVC 2017.

@sphaero It works without curve on all my platforms and configurations.

**Comment by dekel2003** [comment]
@bluca 
The issue is also visible on the build machine from [May 11th](https://ci.appveyor.com/project/zeromq/zyre/builds/32800819/job/y0of88uslognw3mv)

on self test,
lines 1487 to 1539.
peers with curve are marked with "ready=no", then become evasive, silent and quit.
