### ISSUE TITLE
chat example - problems when running large numbers of nodes

### ISSUE THREAD

**Issue by dcrowe** [zeromq/zyre#677]
Hi, I've been running some scale tests with Zyre and have run into a problem when running ~50 nodes across two PCs. I hoping you can give me some pointers to resolve the problem.

I'm running the chat example on two computers across a wifi network. I'm running 25 nodes on each:
> for i in `seq 25`
> do
>     sleep 600 | LD_LIBRARY_PATH=/tmp /tmp/chat $HOSTNAME-$i wlan0 &
> done

When I run this number of nodes, I start to see some nodes leave and then immediately re-join the chat:
> dev-daniel-6 has left the chat
> dev-daniel-6 has joined the chat
> dev-daniel-16 has left the chat
> dev-daniel-16 has joined the chat
> dev-daniel-9 has left the chat
> dev-daniel-9 has joined the chat
> dev-daniel-8 has left the chat
> dev-daniel-8 has joined the chat

On the other PC, I start to see messages like:
>  is being silent
>  is being evasive

* This seems to repeats every 30s.
* Messages seem to be lost sometimes, but not always.

**Comment by dcrowe** [comment]
I forgot to mention that I've made one change to the chat example to set the wifi interface.

**Comment by sphaero** [comment]
I don't see any errors and "messages seem to be lost..." on a wifi network also seems a feature... :slightly_smiling_face: 

The silent and evasive warnings are normal if you stress a network that much.

**Comment by dcrowe** [comment]
I was a bit unclear about my observations:

1. It is the same 4 nodes that are re-connecting every 30seconds. Other nodes appear unaffected. To me this implies that those particular nodes are getting into a bad state.

2. Other silent/evasive warnings do not include the node's name. Has something gone wrong here if the node was able to join the group, but it's name isn't known?

**Comment by sphaero** [comment]
It's a bit hard to tell like this. Best would be to test on a single machine using an ipc transport for example. If the errors would then show as well we have a lead. The silent and and evasive warning show up when a node is not responding within a specific time frame.

**Comment by sphaero** [comment]
see here: https://github.com/zeromq/zyre/blob/master/src/zyre_node.c

**Comment by sphaero** [comment]
I mean: https://github.com/zeromq/zyre/blob/700502c73cb8546b0a607413140fe89ef5e6a34b/src/zyre_node.c#L1498

**Comment by dcrowe** [comment]
Thanks. I'll take a look and see if I can dig up some more info.
