### ISSUE TITLE
building android version not working

### ISSUE THREAD

**Issue by mrabbah** [zeromq/zyre#679]
Hello I tried to build android version for both master or tag v2.0.0 and really it is a miss, a lot of mistakes are made, for example you fixed checking specific versions of android of the toolchain and specific android version, you must test the installation in fresh computer and update the READ.ME:

for example: 
local CPP="${TOOLCHAIN_PATH}/${TOOLCHAIN_HOST}-cpp"
    local CC="${TOOLCHAIN_PATH}/${TOOLCHAIN_HOST}-gcc"
    local CXX="${TOOLCHAIN_PATH}/${TOOLCHAIN_HOST}-g++"
    local LD="${TOOLCHAIN_PATH}/${TOOLCHAIN_HOST}-ld"
    local AS="${TOOLCHAIN_PATH}/${TOOLCHAIN_HOST}-as"
    local AR="${TOOLCHAIN_PATH}/${TOOLCHAIN_HOST}-ar"
    local RANLIB="${TOOLCHAIN_PATH}/${TOOLCHAIN_HOST}-ranlib"

Those files does not exist any more in the toolchain, in many other place you hardcodes for example those path: android-ndk-r21d/platforms/android-8, android-ndk-r21d/platforms/android-9 , android-ndk-r21d/platforms/android-14.
But those folder doe not exist any more.

It is really a miss I wast 3 days to build the android ndk lib without success.

**Comment by sailaja-nagireddy** [comment]
Can you please share what was attempted and the errors you were seeing, along with the details of the environment?

**Comment by sailaja-nagireddy** [comment]
@mrabbah Are you still facing the issue?

**Comment by mrabbah** [comment]
Yes, I tried to build it in OSX (MacBook Pro), like I said a lot of things are hardcoded in the source code, so it will work only on the device of the person who write the source code, to reproduce the problem it is easy, just try to follow instructions on README.ME on fresh installed operating system. If you solve the problem I think you must update code and README.ME for new instructions.
I tried another way, I implemented ZRE specifications to be Java native project based on jyre, I was able to implement the specification with success, I will soon share the source code with the community.

**Comment by sailaja-nagireddy** [comment]
Thank you for your response.  After following the instructions from the [readme](https://github.com/zeromq/zyre/blob/master/builds/android/README.md), below is the resulting error.
```
Android (arm64) build failed for the following reasons:
  Could not find [g]readelf
```
Reason for this is that neither `readelf` nor `greadelf` were present on the `macOS Catalina` system that was used for the build, but equivalent binaries were found in the downloaded `ndk` folder.

Here is the diff that helped the build.
```
╰─❯ git diff android_build_helper.sh
diff --git a/builds/android/android_build_helper.sh b/builds/android/android_build_helper.sh
index bd09f1aa..29cced1d 100644
--- a/builds/android/android_build_helper.sh
+++ b/builds/android/android_build_helper.sh
@@ -267,7 +267,10 @@ function android_build_verify_so {
     fi
     android_build_check_fail

-    if command -v readelf >/dev/null 2>&1 ; then
+    local READELF="${TOOLCHAIN_PATH}/${TOOLCHAIN_HOST}-readelf"
+    if command -v ${READELF} >/dev/null 2>&1 ; then
+        local readelf_bin="${READELF}"
+    elif command -v readelf >/dev/null 2>&1 ; then
         local readelf_bin="readelf"
     elif command -v greadelf >/dev/null 2>&1 ; then
         local readelf_bin="greadelf"
```

Is this consistent with your observation(s) as well?

**Comment by sphaero** [comment]
@sailaja-nagireddy would it possible for you to provide a pull request for this in zproject?

See: https://github.com/zeromq/zproject/blob/820336195641e187ed7527ccd85af77349992566/zproject_android.gsl#L238

Zproject is the tool that creates all the build scripts. Fixing in this in there fixes it for all projects. If you need help let me know.

**Comment by sailaja-nagireddy** [comment]
Sure will give it a try.

**Comment by sailaja-nagireddy** [comment]
Opened this as an issue (https://github.com/zeromq/zproject/issues/1269) in zproject's issue tracker, and will raise a pull request once tested.

**Comment by sailaja-nagireddy** [comment]
@sphaero Above discussed resolution is part of the `zproject` master.  How will this change be propagated to the dependent projects?  Is this a manual or automated process?  Please advise if there is any intervention required.

**Comment by sphaero** [comment]
Your fix is now in zproject master. So now the CI tests will fail until we regenerate the build environment and send a PR of the change. This won't happen automatically!

You can do this as well if you want. Just [install gsl and zproject](https://github.com/zeromq/zproject#installation). Once installed run `gsl project.xml` from the git root directory. You'll notice the changes it does by a `git status`.

**Comment by sailaja-nagireddy** [comment]
I created the pr https://github.com/zeromq/zyre/pull/681 to reflect the changes made to zproject.  This is probably required to be done in zproject dependent projects such as libzmq and czmq, right?  Thank you for helping me with the required information.

**Comment by sailaja-nagireddy** [comment]
@sphaero The pr #681 addresses updates to android build script `builds/android/android_build_helper.sh`, where as travis logs are indicating that the failure is due to a missing file zre_msg.xml expected by the ci build script.  Any thoughts?

Here are the last few lines of the [travis log](https://travis-ci.org/github/zeromq/zyre/jobs/732687971).
```
5b2defe72b4a: Pull complete
bcdadce2e4b7: Pull complete
Digest: sha256:cfef7b3829da905da0d60ab011834a71d9caca6e46fdbcb73860032552cfc1af
Status: Downloaded newer image for zeromqorg/zproto:latest
gsl/4 E: Error processing zre_msg.xml...
Could not find XML file: zre_msg.xml
The command "./ci_build.sh" exited with 1.
```

**Comment by sailaja-nagireddy** [comment]
@mrabbah Can you please update if the provided solution helped, so that this issue can be closed?  Failing CI builds is being tracked separately as a part of issue #682 to address the issues from travis and appveyor.

**Comment by sphaero** [comment]
Not sure what's happening with the zproto check. @sappo any clues?

It's not related to this issue so please move that to #682
