### ISSUE TITLE
zyre 2.0.1 release missing release artifact

### ISSUE THREAD

**Issue by chenrui333** [zeromq/zyre#685]
👋  the latest release does not have release artifact (vs release 2.0.0), thanks!

**Comment by sappo** [comment]
Hi rui,
I'm working on it  ;) It was an permission problem that prevented Travis
from uploading the artifacts. Also Travis was really really slow on Friday
so I ran out of time fixing it.

//Kevin

rui <notifications@github.com> schrieb am So., 24. Jan. 2021, 00:11:

**Comment by sappo** [comment]
*tar.gz and *zip files are now available. I'm still working on the android release files!

**Comment by stephan57160** [comment]
Hello Kevin,

Does it mean there will some more COMMITS for 2.0.1 ?

Regards,

Stephan.


Le 25-Jan-21 à 08:58, Kevin Sapper a écrit :

**Comment by sappo** [comment]
Hi Stephan,
no I'll build them locally and upload them by hand.

Am Mo., 25. Jan. 2021 um 09:00 Uhr schrieb Stephan Guilloux <
notifications@github.com>:

**Comment by chenrui333** [comment]
Thanks @sappo, gonna try out in [this PR](https://github.com/Homebrew/homebrew-core/pull/69962)

**Comment by sappo** [comment]
I just added missing android jars for the release.
