### ISSUE TITLE
How to properly install dll files with python bindings on Windows

### ISSUE THREAD

**Issue by franciszekjuras** [zeromq/zyre#687]
I'm fairly new to Python and was wondering what's the proper way to install python bindings with dlls on Windows.
I compiled zyre and its dependencies using vcpkg. I found out that I need to execute `setup.py` too install python bindings for zyre and each of its dependencies.
But where should go dll files? Should they be distributed in project files or in the same place where python packages are installed?

**Comment by sappo** [comment]
@sphaero can you assist?

**Comment by sphaero** [comment]
woops, I completely missed this one. However I have no experience with windows in this matter. On other platforms it's quite simple. I suspect the DLL needs to go where the executable is or in one of the pythons dirs for windows but I'm curious as well.
