### ISSUE TITLE
Publish to a group without subscribing

### ISSUE THREAD

**Issue by cowratt** [zeromq/zyre#712]
For network performance reasons, I'd like to (if possible) have a node publish to a group without subscribing to it. Consider the case where I want to have 50 nodes publishing and 5 nodes listening. Currently, messages are sent everywhere, so if each publishing node publishes 10 messages per second, we get 10 x 50 x 54 = ~27,000 messages per second across the network.

A solution would be to create 50 different groups so that each node can publish to only itself and the five listening nodes, but ideally, it would be nice to be able to "unsubscribe" a node from receiving messages

**Comment by sthoduka** [comment]
You can shout to a group without actually joining it
