### ISSUE TITLE
question about "Zyre is reliable, and loses no messages even when the network is heavily loaded."

### ISSUE THREAD

**Issue by calvin2021y** [zeromq/zyre#734]
since there is no discussions section, I will drop the question here.

in the  `Scope and Goals`, 
```md
Zyre provides reliable group messaging over local area networks. It has these key characteristics:

Zyre is reliable, and loses no messages even when the network is heavily loaded.

Uses reliable Dealer-Router pattern for interconnection, assuring that messages are not lost unless a peer application terminates.
```

The documents cloud be more clear about ` loses no messages`,   Under what conditions will the message not be lost ?

I can think of there case here:

1) recipient crash before read message
2) recipient crash after read message
3) send crash before send message

Is there a persistence layer and ack mechanism responsible for this task?  

In what conditions the message will lost， maybe add this list into document will help to clear it.

**Comment by sappo** [comment]
Hi @calvin2021y, 
loses no message refers to networking issues. If a peer crashes that is something your application code has to handle.

**Comment by calvin2021y** [comment]
thanks for explain. maybe add some information into readme to clarify this
